### PR TITLE
Introduce two operations to consumption API, price sheet and updated budget

### PR DESCRIPTION
**Pull request by lmazuel**
Fix Go conf

Thanks you for your contribution to the Azure-SDK-for-Go! We will triage and review it as quickly as we can.

As part of your submission, please make sure that you can make the following assertions:

 - [ ] I'm not making changes to Auto-Generated files which will just get erased next time there's a release.
   - If that's what you want to do, consider making a contribution here: https://github.com/Azure/autorest.go
 - [ ] I've tested my changes, adding unit tests where applicable.
 - [ ] I've added Apache 2.0 Headers to the top of any new source files.
 - [ ] I'm submitting this PR to the `dev` branch, or I'm fixing a bug that warrants its own release and I'm targeting the `master` branch.
 - [ ] If I'm targeting the `master` branch, I've also added a note to [CHANGELOG.md](https://github.com/Azure/azure-sdk-for-go/blob/master/README.md).
 - [ ] I've mentioned any relevant open issues in this PR, making clear the context for the contribution.

### CODE REVIEW

**Comment by lmazuel** [comment]
@marstr That's your first auto PR ;)
For some reason the branch was created, but not the PR, so I created it manually (investigation in progress)

**Comment by marstr** [comment]
Ooooh, that's interesting. I don't think we're super dedicated to the checklist. If it's getting in the way, we can just get rid of it. Do you agree, @jhendrixMSFT?

**Comment by jhendrixMSFT** [comment]
Hmm I'm a bit torn on this.  While it does clutter up the PR a bit, it is nice to have this info in your face so you don't forget something.  Are we sure the template is the problem?

**Comment by lmazuel** [comment]
@jhendrixMSFT actually no, the template wasn't the problem, it's an automation bug :)

**Comment by marstr** [comment]
@jhendrixMSFT just to close the loop on our conversation offline, I confirmed with @lmazuel that there are no action items around the templates.

**Comment by marstr** [comment]
Closing for now, in response to #1057. These changes will be incorporated shortly.

**Pull request closed without merging**
