### PR TITLE
Updating to Joel's latest PR for go-amqp that removes the session mux

### PR DESCRIPTION
**Pull request by richardpark-msft**

### CODE REVIEW

**Comment by richardpark-msft** [comment]
@jhendrixMSFT , getting a failure with your latest patch, specifically when using websockets:

=== RUN   TestNewClientWithWebsockets
    /home/ripark/src/_/sb-test-latest-go-amqp/sdk/messaging/azservicebus/client_test.go:110:
        	Error Trace:	client_test.go:110
        	Error:      	Received unexpected error:
        	            	(connlost): invalid protoHeader
        	Test:       	TestNewClientWithWebsockets

**Comment by jhendrixMSFT** [comment]
@richardpark-msft where can I find more info on the failing test?

**Comment by jhendrixMSFT** [comment]
@richardpark-msft I have a repro now, investigating...

**Comment by jhendrixMSFT** [comment]
@richardpark-msft fix applied, great catch.

**Pull request closed without merging**
