### PR TITLE
Minor release v34.1.0

### PR DESCRIPTION
**Pull request by ArcturusZhang**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] The PR targets the `latest` branch.
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] Apache v2 license headers are included in each file.
 
[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
This just adds back the packages that were inadvertently deleted right?

**Comment by ArcturusZhang** [comment]
> This just adds back the packages that were inadvertently deleted right?

A new network package of api version 2019-08-01 is brand new.
Maybe I should change the order of entries in CHANGELOG to highlight this real new package.

**Comment by tombuildsstuff** [comment]
👋 any chance we could get https://github.com/Azure/azure-sdk-for-go/pull/5914 into this minor release, since that's not a breaking change & has been merged? Thanks!

**Comment by ArcturusZhang** [comment]
> 👋 any chance we could get #5914 into this minor release, since that's not a breaking change & has been merged? Thanks!

No problem

**Pull request merged**
