### PR TITLE
[azopenai] Updating for the 2024-02-15-preview

### PR DESCRIPTION
**Pull request by richardpark-msft**
- Added back the process to compile the .tsp and generate from our own local swagger output
- Adding in TTS support via GetAudioSpeech()

APIView: https://apiview.dev/Assemblies/Review/32a4f4709b2e46a2814de07d1cbbbdd7?revisionId=2ffb3f10ce26452c8bd562f70e909a42&diffOnly=False&doc=False&diffRevisionId=ffd3552ede9e4f40bac98baa3ab9353d

### CODE REVIEW

**Review by richardpark-msft — COMMENTED** [review]
/azp run go - azopenai

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by richardpark-msft** [comment]
(Failures are due to some oversubscribed resources, which I can't change. I'm reducing the number of tests in the problematic area)

**Pull request merged**
