### PR TITLE
Fixing ModuleName to be compliant with the standard

### PR DESCRIPTION
**Pull request by richardpark-msft**
Fixing all the outdated projects - ModuleName is intended to be the full module path, not just the folder name.

Also, updated the template project.

### CODE REVIEW

**Comment by richardpark-msft** [comment]
@ronniegeraghty, this will affect what we report, as the package name, in our user agent. I'm not sure if we have any reports based on the string.

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by richardpark-msft** [comment]
(overrode approval on this - looks like @jhendrixMSFT and I still have some folders that aren't covered by our current CODEOWNERS permissions.

**Comment by ronniegeraghty** [comment]
> @ronniegeraghty, this will affect what we report, as the package name, in our user agent. I'm not sure if we have any reports based on the string.

None that are still working and I don't believe we use the package name. Since our telemetry data will come from the different services data streams they are already divided by service. Event Grid might be interesting though. I don't know if they have separate data streams for event grid basic vs namespaces. The system events package doesn't actually make http requests right? it's just a catalog of the different system event types, right? So we'd never see telemetry from that library.

**Comment by jhendrixMSFT** [comment]
It won't impact the name used in telemetry as we extract the package name (e.g. `azfoo`) from the fully qualified module name.

**Pull request merged**
