### PR TITLE
v36.2.0

### LINKED ISSUE #6276: There is no available SQL API with all supported clients & operations
### Bug Report

- What happened?

We have to import upwards of three different SQL api versions to fully support the sql resources:
`github.com/Azure/azure-sdk-for-go/services/preview/sql/mgmt/2017-03-01-preview/sql`
`github.com/Azure/azure-sdk-for-go/services/preview/sql/mgmt/2017-10-01-preview/sql`
`github.com/Azure/azure-sdk-for-go/services/preview/sql/mgmt/2018-06-01-preview/sql`

so we get this:
```
import (
	sql201703 "github.com/Azure/azure-sdk-for-go/services/preview/sql/mgmt/2017-03-01-preview/sql"
	"github.com/Azure/azure-sdk-for-go/services/preview/sql/mgmt/2017-10-01-preview/sql"
	sql201806 "github.com/Azure/azure-sdk-for-go/services/preview/sql/mgmt/2018-06-01-preview/sql"
)

type Client struct {
	ElasticPoolsClient *sql.ElasticPoolsClient
	ElasticPoolsClient                                 *sql.ElasticPoolsClient
	DatabaseVulnerabilityAssessmentRuleBaselinesClient *sql201703.DatabaseVulnerabilityAssessmentRuleBaselinesClient
	ServerSecurityAlertPoliciesClient                  *sql201703.ServerSecurityAlertPoliciesClient
	ServerVulnerabilityAssessmentsClient               *sql201806.ServerVulnerabilityAssessmentsClient
}
```

and it becomes awfully confusing.

- What did you expect or want to happen?
one unified API containing all clients and operations

- How can we reproduce it?
try to provision all sql resources in a project

- Anything we should know about your environment.
nope

### PR DESCRIPTION
**Pull request by ArcturusZhang**
This should also resolves #6276 

- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] The PR targets the `latest` branch.
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] Apache v2 license headers are included in each file.
 
[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Rebased to master

**Comment by tombuildsstuff** [comment]
@ArcturusZhang 👋 any chance we could get https://github.com/Azure/azure-rest-api-specs/pull/7746 included in this release?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang 👋 any chance we could get [Azure/azure-rest-api-specs#7746](https://github.com/Azure/azure-rest-api-specs/pull/7746) included in this release?

Sure, I will wait for 7746 getting merged

**Comment by tombuildsstuff** [comment]
@ArcturusZhang awesome, thanks a bunch :)

**Pull request merged**
