### PR TITLE
[KeyVault] regenerate azcertificates from 7.3 swagger

### PR DESCRIPTION
**Pull request by seankane-msft**
regenerating from latest GA swagger

### CODE REVIEW

**Review by mccoyp — APPROVED** [review]
It looks like recordings were manually updated instead of being generated by new test runs -- is that for a particular reason?

**Comment by seankane-msft** [comment]
> It looks like recordings were manually updated instead of being generated by new test runs -- is that for a particular reason?

Not a great one, running a live test to verify the tests pass.

**Pull request merged**
