### PR TITLE
Use common OIDC token env vars in post scripts

### PR DESCRIPTION
**Pull request by benbp**
This should fix the weekly pipelines for azidentity and azcontainerregistry (this one still fails, but it's not engsys' fault anymore).

Relies on https://github.com/Azure/azure-sdk-tools/pull/9099 going in first.

### CODE REVIEW

**Comment by chlowell** [comment]
#23548 will green azidentity CI

**Review by RickWinter — APPROVED** [review]
LGTM, Please get @chlowell to review before checking in

**Comment by benbp** [comment]
> Any plans to do this cross-language? I am definitely interested in this for JS - keyvault and identity would both benefit 👍

Yep! https://github.com/Azure/azure-sdk-for-js/pull/31335

**Comment by benbp** [comment]
@chlowell I'm not sure why yet, but the container registry tests do not seem to be picking up the right audience when running in sovereign cloud contexts (https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4210366&view=logs&j=6617e070-ecf6-5e84-d74f-69d70ef2cee7&t=df873bcd-9288-585c-3c23-e81f89f38ac8&l=1004). It predates these changes but may have coincided with our federated auth move.

**Comment by chlowell** [comment]
There's a bug. It might predate federated auth or I might have added it 😇 

Try https://github.com/chlowell/azure-sdk-for-go/commit/cf51e8b7f52df29c58b03d09499646eb3ec9ff11

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
