### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by qt-luigi**
I fixed typo from "programatically" to "programmatically" in README.md. Please check it.

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Hi @qt-luigi thanks for contributing to azure-sdk-for-go!

This PR looks great to me, but we are currently not using the branch `latest` anymore. Due to the merging mechanism, the `latest` branch is diverging larger and larger comparing with the `master` branch, and releasing things with `latest` branch as a middle-ground is very painful with a lot of merge conflicts every time which will never get resolved.

Could you please retargeting this PR to `master` branch? I will update the PR template very soon.

**Comment by qt-luigi** [comment]
Hi @ArcturusZhang, Thanks for responding this tiny PR.

I read this repo's CONTRIBUTING.md, and I tried PR to `latest` branch. You might want to update CONTRIBUTING.md about PR branch.

Yes, I could retargeting this PR to master branch. Sorry I am a beginner for GitHub. Please teach me. What should I do?

**Comment by ArcturusZhang** [comment]
Hi @qt-luigi thanks for your suggestion and sorry for the confusion, I will make a PR to update the CONTRIBUTING.md accordingly.

Since `latest` and `master` are highly diverged, it would be not so easy to retarget your PR... (FYI, you can find an `edit` button beside the title, click it and you can change the target PR. But as a result, you will get a lot of conflicts) Therefore I suggest you to close this PR and recreating your change based on the master branch and then open a new PR.

Thank you

**Comment by qt-luigi** [comment]
Hi @ArcturusZhang thanks for advising me and I also appreciate you quick updating CONTRIBUTING.md.

Master branch updated to v43.1.0 but you didn't fix this PR typo. Thanks for waiting and giving me a chance.

I created a new PR for master branch (#10142). This PR close. Please check it. Thank you.

**Pull request closed without merging**
