### PR TITLE
[Release] sdk/resourcemanager/recoveryservices/armrecoveryservicesbackup/4.0.0

### PR DESCRIPTION
**Pull request by Alancere**
https://github.com/Azure/sdk-release-request/issues/4714

### CODE REVIEW

**Comment by Alancere** [comment]
The breaking changes are introduced and approved in [this PR](https://github.com/Azure/azure-rest-api-specs/pull/25791).

**Comment by Alancere** [comment]
@microsoft-github-policy-service rerun

**Comment by raych1** [comment]
@Alancere , let's wait until the service response on the breaking change question in JAVA release request.

**Review by tadelesh — APPROVED** [review]

**Pull request merged**
