### PR TITLE
Fixed IsResourceNotFoundError.

### PR DESCRIPTION
**Pull request by aznashwan**
Fixed the IsResourceNotFoundError function.
The type to cast to had to be changed due to the recent changes in the definition of the getAzureError function.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
I'm not sure why this is the case, we used to return pointers, now we don't. So the old code sounds right to me @aznashwan?

**Comment by aznashwan** [comment]
I have trouble getting why this happens as well.
I strongly suspect that it's because casting an interface auto-implies some pointer vodoo.
The point is that after the change to getAzureError if you try to cast to the struct it fails; saying that the value it got was of type *AzureError which is uncastable to AzureError...

**Comment by ahmetalpbalkan** [comment]
@aznashwan removing your `pkg/` dir, `go get -u` and rebuilding may help. Apparently you still have the old code somehow. From what I can tell, this shouldn't be happening. Please let us know if it still happens after building again.

**Comment by aznashwan** [comment]
@ahmetalpbalkan after some internal code review I realised I had written not one; but two if statements which were complete utter bogus :disappointed: 

Thank your for your patience; and my apologies for the misunderstanding.

**Pull request closed without merging**
