### PR TITLE
Update to use latest github.com/google/go-github API

### PR DESCRIPTION
**Pull request by flyn-org**
I am helping to package azure-sdk-for-go  on Fedora, and this change would make that easier. This aims to update azure-sdk-for-go to use version 53 of the  github.com/google/go-github API.

I am still trying to determine whether the existing tests are sufficient to validate this change. What do you think?

### CODE REVIEW

**Comment by flyn-org** [comment]
@microsoft-github-policy-service agree

**Comment by flyn-org** [comment]
This is still active.

**Comment by jhendrixMSFT** [comment]
Looks like there's a missing `go mod tidy`. Can you please update your branch from `main` and tidy up the required packages?

**Comment by jhendrixMSFT** [comment]
@tadelesh since this is tooling used by your team, I'll leave it to you to review/merge.

**Comment by flyn-org** [comment]
> Looks like there's a missing `go mod tidy`. Can you please update your branch from `main` and tidy up the required packages?

I just forced-pushed these changes.

**Review by tadelesh — APPROVED** [review]

**Pull request merged**
