### PR TITLE
Added setuping field to NewBlockBlobClientWithSharedKey

### PR DESCRIPTION
**Pull request by godvlpr**
Added setup of one of the field (sharedKey) to `azblob.NewBlockBlobClientWithSharedKey` constructor. Problem was about the using client generated by this constructor.
Steps to reproduce:

Create client using `azblob.NewBlockBlobClientWithSharedKey`
Call `GetSASToken(permissions BlobSASPermissions, start time.Time, expiry time.Time) (SASQueryParameters, error)`
Expecting result is returning structure `azblob.SASQueryParameters`.
Actual result is error: `credential is not a SharedKeyCredential. SAS can only be signed with a SharedKeyCredential.`
It happens be cause `azblob.SASQueryParameters` has rows for checking of existing the `sharedKey`:
```
if b.sharedKey == nil {
		return SASQueryParameters{}, errors.New("credential is not a SharedKeyCredential. SAS can only be signed with a 
        SharedKeyCredential")
	}
```
Problem can be fixed if in the `azblob.NewBlockBlobClientWithSharedKey` field sharedKey will be set.

### CODE REVIEW

**Comment by mohsha-msft** [comment]
Can you please target the dev-azblob-2 branch instead of main?

**Comment by godvlpr** [comment]
Sure, done

**Comment by godvlpr** [comment]
Do, I need to clone dev-azblob-2 and do fix with code from that branch? Or this PR is okay to?

**Comment by godvlpr** [comment]
Okay, I see conflicts, let me clone dev-azblob-2 branch and fix with that code, i'll recreate PR

**Pull request closed without merging**
