### PR TITLE
Update default storage API version to 2018-03-28

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Updated string-to-sign algorithm for SAS tokens to support 2018-11-09.

- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] The PR targets the `latest` branch.
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] Apache v2 license headers are included in each file.
 
[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@tombuildsstuff @kt how hard would it be to ingest this into Terraform to see if anything breaks?  My hope is to add some of the missing functionality in this API version to unblock Terraform scenarios.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT oh cool, thanks! To get the tests running is pretty easy - I’ll try and kick off a test run today. That said it may be worth holding off adding support for the new functionality for the moment.

I started looking into generating our own Data Plane SDK for Storage, but couldn’t find the Swagger files to generate from - so instead I ended up prototyping our own using the standard go-discover libraries (eg including Context). Whilst we’re just prototyping it (and adding tests) to see if that’s viable at this stage, I’m wondering if that approach (and possibly upstreaming it) would be better longer-term than trying to determine what features are missing from the old SDK - WDYT?

Thanks!

**Comment by jhendrixMSFT** [comment]
So there is a swagger for this floating about internally but has not been made public for reasons I don't understand.  I plan on following up on that but I'm not super-optimistic about it.  In addition, we never back-ported XML support to the v2 code generator so even with a swagger we would still be blocked until this happened.
I forgot about lack of context in the current storage package, that's a bummer and splicing this in might be clunky.  Really my hope was that I could spend half a day to implement some low-hanging fruit to get you unblocked, e.g. static web sites or whatever APIs you needed.

**Comment by tombuildsstuff** [comment]
@vladbarosan @jhendrixMSFT tests look good to me:

Screenshot 2019-05-29 at 17 17 05

**Pull request merged**
