### PR TITLE
Various cleanup in azappconfig

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Convert slices of types in-place.
Fixed up parameter name for creating snapshots.
Correct casing for ETag.
Removed duplicate KeyValueFilter type.
Add spans for new APIs.

Fixes https://github.com/Azure/azure-sdk-for-go/issues/22151

### CODE REVIEW

**Review by chlowell — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@weshaggard is check enforcer stuck?

**Comment by weshaggard** [comment]
@jhendrixMSFT it was an artifact of some devops outages yesterday but it should be good now.

**Pull request merged**
