### PR TITLE
azidentity: Adding SubjectName/Issuer support

### LINKED ISSUE #11874: Support SubjectName/Issuer (SNI) certificate authentication for Service Principals
Support SubjectName/Issuer (SNI) certificate authentication for Service Principals

### PR DESCRIPTION
**Pull request by catalinaperalta**
Fixes #11874

### CODE REVIEW

**Review by jhendrixMSFT — APPROVED** [review]
It looks good, do you have a way to test that the header is correct?

**Comment by catalinaperalta** [comment]
> It looks good, do you have a way to test that the header is correct?

The short and I would say is not a perfect way to test it. But what I was thinking about is maybe comparing the number of certificates in the slice and possibly encoding the certificate in the test and comparing it to the value in the header? That could be a way to test it. Also, just an FYI, I did manually perform a live test against AAD with this feature set and successfully authenticated since I received an access token in response.

**Comment by jhendrixMSFT** [comment]
Good idea on the test, and glad that the manual test worked.

**Comment by catalinaperalta** [comment]
Added the test! Could only check up to the JWT's header, since both the payload and signature have random or unique characters generated in them.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
