### PR TITLE
Use subscription configuration variables for openai live tests

### PR DESCRIPTION
**Pull request by benbp**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by richardpark-msft** [comment]
(one key was out of date, but there's some other failures relating to identity)

**Comment by benbp** [comment]
@richardpark-msft did you want to approve?

**Comment by richardpark-msft** [comment]
> @richardpark-msft Richard Park (DEVDIV) FTE did you want to approve?

Let's get it to pass. I added in some variables I added in the other pipeline as well.

**Comment by benbp** [comment]
@richardpark-msft ah sorry, when I commented all the tests were green so I thought you had.

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
