### PR TITLE
prepare for v12.0.0-beta

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Thanks you for your contribution to the Azure-SDK-for-Go! We will triage and review it as quickly as we can.

As part of your submission, please make sure that you can make the following assertions:

 - [ ] I'm not making changes to Auto-Generated files which will just get erased next time there's a release.
   - If that's what you want to do, consider making a contribution here: https://github.com/Azure/autorest.go
 - [ ] I've tested my changes, adding unit tests where applicable.
 - [ ] I've added Apache 2.0 Headers to the top of any new source files.
 - [ ] I'm submitting this PR to the `dev` branch, or I'm fixing a bug that warrants its own release and I'm targeting the `master` branch.
 - [ ] If I'm targeting the `master` branch, I've also added a note to [CHANGELOG.md](https://github.com/Azure/azure-sdk-for-go/blob/master/README.md).
 - [ ] I've mentioned any relevant open issues in this PR, making clear the context for the contribution.

### CODE REVIEW

**Comment by sptramer** [comment]
@jhendrixMSFT - Please ping me when this PR is merged, I have been waiting on v0.12 to start doing documentation tasks for GA. Thanks!

**Comment by jhendrixMSFT** [comment]
@sptramer You'll want to follow up with @marstr or @joshgav as I'll be OOF for two weeks after today.  Also note this is just merging v12 into dev, we'll still need to merge dev into master when we're ready to release.

**Comment by jhendrixMSFT** [comment]
Generated from a snapshot of specs repo on 12/15/2017 with various config file updates.  You can find it https://github.com/jhendrixmsft/azure-rest-api-specs/tree/golang

**Comment by joshgav** [comment]
@jhendrixMSFT based on your comment in https://github.com/Azure/azure-sdk-for-go/pull/909#issuecomment-352130680 i updated the title. thanks!

**Comment by vladbarosan** [comment]
For reference, changes will be made through the here https://github.com/Azure/azure-sdk-for-go/pull/916 which is based on the current one

**Pull request closed without merging**
