### PR TITLE
Add ContentType to PutBlobOptions

### PR DESCRIPTION
**Pull request by ncw**
I haven't written tests for this yet but I'm happy to if you think this approach is OK.

### CODE REVIEW

**Comment by ncw** [comment]
Note that I've updated the commit with the other missing headers.

**Comment by mcardosos** [comment]
Hello again @ncw !
The way you can modify this header (and many other headers) is like this...
``` go
b := container.GetBlobReference("myBlob")
b.Properties := BlobPoroperties{
    ContentType:     "application/json",
}
```

**Comment by ncw** [comment]
Ah, OK!  Yes that works :-)

And that should have been obvious since I'm updating the metadata the same way...

Want me to send a PR adding a bit more docs to `CreateBlockBlobFromReader`?

**Comment by mcardosos** [comment]
@ncw PRs are always welcome :D

**Comment by ncw** [comment]
OK I'll send some changes to the docs for the bits I found confusing!

Thanks for your help.

**Pull request closed without merging**
