### PR TITLE
Generated the Application Insights SDK

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Should probably wait for https://github.com/Azure/azure-rest-api-specs/pull/757 to be merged before merging this

- Implemented CRUD support for the Application Insights endpoints in the SDK

### CODE REVIEW

**Comment by jeffwilcox** [comment]
Hi, I'm going to have a machine account close and re-open this pull request. This sometimes is sufficient to bump the CLA subsystem to evaluate the CLA. Sorry for any inconvenience!

**Comment by tombuildsstuff** [comment]
Any chance someone could take a look at this PR please? :)

**Comment by marstr** [comment]
Howdy Tom! Sorry for the lack of activity here. Per your comment at the top, we were waiting to look at this until [this pull request](https://github.com/Azure/azure-rest-api-specs/pull/757) was accepted in case another iteration of generation is required. Seem reasonable? We will continue to triage this pull request along with all other open pull-requests, it will not go forgotten.

**Comment by tombuildsstuff** [comment]
@marstr thanks for taking a look :)

That's fair enough, I guess I was hoping for some guidance given the Rest API Specs team haven't had a chance to look at this either.

I was half hoping that this would make it into v7 / v8 of the SDK tbh but alas. For now I'm going to implement support for Application Insights into [Riviera](https://github.com/jen20/riviera) - because I don't think this'll be available in an SDK before (presumably v9?) in late January?

**Comment by salameer** [comment]
Hi @tombuildsstuff well the good news is that we have contacted the AI team for the other PR and they're intending to review it, which will unblock this issue eventually. the little bit of unfortuante new is I dont have enough clarity on the timelines yet :( .. what we can promise for now is that we'll keep following up (Nagging :)) on the other PR to happen and keep you posted of updates here

**Comment by tombuildsstuff** [comment]
@salameer thanks a bunch :)

**Comment by marstr** [comment]
Alright, @tombuildsstuff! The time has come to *finally* resolve this. It seems that the swaggers for the [insights service are done](https://github.com/Azure/azure-rest-api-specs/tree/master/arm-insights), and that we can generate them in v10.

**Comment by tombuildsstuff** [comment]
@marstr Awesome - I'll close this PR for the moment then :)

One minor thing, I think you meant to link to [the `arm-appinsights` package](https://github.com/Azure/azure-rest-api-specs/tree/master/arm-appinsights) rather than the `arm-insights` one, which from what I can tell is what's now called Azure Monitoring?

Thanks :)

**Pull request closed without merging**
