### PR TITLE
Enable federated auth in messaging pipelines

### PR DESCRIPTION
**Pull request by chlowell**

### CODE REVIEW

**Comment by chlowell** [comment]
Blockers:
- azeventgrid doesn't pass its coverage bar
- aznamespaces has an `Example_publishAndReceiveCloudEvents` which executes and directly uses DefaultAzureCredential
- azservicebus is affected by #23208

**Comment by richardpark-msft** [comment]
> aznamespaces has an Example_publishAndReceiveCloudEvents which executes and directly uses DefaultAzureCredential

Feel free to disable it for now (just remove the // Output: line), I can figure it out at some point.

> azeventgrid doesn't pass its coverage bar

You can lower it for now. I have to come back and re-enable all of it's recordings, I believe.

> azservicebus is affected by https://github.com/Azure/azure-sdk-for-go/issues/23208

I think we're just stuck with this one for now.

All the other changes look fine to me. I don't actually own azwebpubsub, however.

**Review by RickWinter — APPROVED** [review]

**Comment by RickWinter** [comment]
@chlowell @richardpark-msft Is this PR blocked on anything? I'd like to get everything moved to FederatedAuth

**Comment by richardpark-msft** [comment]
> @chlowell @richardpark-msft Is this PR blocked on anything? I'd like to get everything moved to FederatedAuth

Nothing on my end - perfectly fine with changes for any packages he touched. 

azwebpubsub isn't owned by me, however.

**Comment by chlowell** [comment]
@richardpark-msft can you approve for messaging? I think Rick owns azwebpubsub by default. Seems like he should count as an owner of messaging as well, but GitHub tells me he owns fewer touched files than you do.

**Review by richardpark-msft — APPROVED** [review]

**Pull request merged**
