### PR TITLE
[DoNotMerge] UUID package switch test

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes https://github.com/Azure/azure-sdk-for-go/issues/3158

- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] Apache v2 license headers are included in each file.
 
[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by dlorenc** [comment]
Hi! Just wondering if this is still planned. I'm trying to track down some dependencies marked vulnerable in some of my projects, and this one is coming up. Is there anything I can do to help swap the packages here?

**Comment by ArcturusZhang** [comment]
Hi @dlorenc this is still planned, but it will not happen in this month's major release. Please stay tuned.

**Comment by dlorenc** [comment]
> Hi @dlorenc this is still planned, but it will not happen in this month's major release. Please stay tuned.

Thanks for the reply! Is there anything I can do to help get this in in time? I don't mind trying to do the swap/testing things out if it's a bandwidth issue.

**Comment by ArcturusZhang** [comment]
> > Hi @dlorenc this is still planned, but it will not happen in this month's major release. Please stay tuned.
> 
> Thanks for the reply! Is there anything I can do to help get this in in time? I don't mind trying to do the swap/testing things out if it's a bandwidth issue.

Well, it is not really a bandwidth issue more of an issue we should not introduce too many breaking changes in one major version and also consideration of the up-coming new year holiday. 
We are planning to do some other improvements, such as [this](https://github.com/Azure/azure-sdk-for-go/issues/14010) which also might be a breaking change across all of the packages (or maybe not).
But testings would be a great help, thanks a lot. We are happy to have any possible feedbacks on the impact of this change.

**Pull request closed without merging**
