### PR TITLE
This enables creating deployments with some additional options

### PR DESCRIPTION
**Pull request by svanharmelen**
A use case example is that without this code it isn’t possible to create a deployment for a custom virtual network/subnet…

See PR #107 for the complete story on this one.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@svanharmelen it looks like tests have some references to the old CreateDeployment method signature (but we're investigating why they're not failing on CI). Can you please fix the tests as well, thanks.

**Comment by ahmetalpbalkan** [comment]
LGTM. Also @svanharmelen did you manually test this if this actually can deploy the VM with specified settings. The comment by @paulmey on the other thread was Azure APIs are sometimes sensitive to  order of the elements in the request XML (although this is not clearly documented). That's why we try to manually test the new implementations as much as we can.

**Comment by svanharmelen** [comment]
@ahmetalpbalkan which tests? I couldn't spot them at first sight...

And yes, see my replies on his comments/questions:

```
@paulmey yes, I certainly tested this :smiley: It's not only reordered but I also added the `Subnet` field and I did more then a few tests today with creating virtual networks and subnets and then adding virtual machines to them.

So during the day I added a few, updated a few existing ones and also deleted a few again. So I would say I touched all operations at least a couple of times.
```

But even through I did test it pretty well, I did also revert the ordering change and replied that as well:

```
@paulmey just reverted the ordering as there isn't any good argument for the reordering other than personal preference. So if you have any experience with the order being picky, let's just keep that in sync with the API docs...
```

**Comment by ahmetalpbalkan** [comment]
@svanharmelen there are two test files:

```sh
$ ack --go CreateDeployment
management/virtualmachine/client.go
27:func (self VirtualMachineClient) CreateDeployment(role Role, cloudServiceName string) (management.OperationId, error) {

management/vmutils/examples_test.go
42:	operationId, err = virtualmachine.NewClient(client).CreateDeployment(role, dnsName)

management/vmutils/integration_test.go
109:		return vmc.CreateDeployment(role, vmname)
189:		return vmc.CreateDeployment(role, vmname)
```

**Comment by svanharmelen** [comment]
Ah... In the vmutils package... Check, will have a look.

**Comment by svanharmelen** [comment]
@ahmetalpbalkan updated the tests...

**Comment by ahmetalpbalkan** [comment]
@svanharmelen can you please rebase your branch on top of master? I just renamed MSOpenTech word in the imports to Azure (that was causing false positives in the CI earlier).

**Comment by svanharmelen** [comment]
Grr... Rebasing => OK, but then squashing it => NOK

Will create yet another PR.

**Comment by ahmetalpbalkan** [comment]
@svanharmelen I will write a blog post about how to squash things. :-)

**Comment by svanharmelen** [comment]
Well I know how to squash commits, no worries :wink: And I also know how to update my fork from a remote source... But when doing a fetch remote, rebase upstream and then a squash, ofter causes me to have older commits in any outstanding PRs based on the branch I'm squashing.

So if you have a good workflow which prevents that, please do write it up and send me the link :smiley:

**Pull request closed without merging**
