### PR TITLE
Storage: Re-enable HTTP endpoints for shared key credential

### PR DESCRIPTION
**Pull request by souravgupta-msft**
Revert the change made in #22183 and #21841.

Discussion with PM and some concerns raised on github for this reveals that Azure Stack and Azurite users either prefer or in some cases forced to use HTTP. Not allowing HTTP from SDK side block their setup. Similar issues were faced by AzCopy and Blobfuse in their pipelines to test against Azurite. Hence reverting back the changes and allowing HTTP with key credentials.

- [x] The purpose of this PR is explained in this or a referenced issue.
- [x] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [x] Tests are included and/or updated for code changes.
- [x] Updates to module CHANGELOG.md are included.
- [x] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go

### CODE REVIEW

**Review by vibhansa-msft — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
Is this just to address the storage emulator? If so, perhaps there's a different solution.

CC @JeffreyRichter

**Review by tasherif-msft — APPROVED** [review]

**Review by gapra-msft — APPROVED** [review]

**Comment by gapra-msft** [comment]
> Is this just to address the storage emulator? If so, perhaps there's a different solution.
> 
> CC @JeffreyRichter

This also addresses environments like Azure Stack or private links where customers either prefer to use HTTP or are forced to use HTTP

**Comment by gapra-msft** [comment]
> Is this just to address the storage emulator? If so, perhaps there's a different solution.
> 
> CC @JeffreyRichter

@jhendrixMSFT This also addresses some environments where customers are either forced to use HTTP or prefer to use HTTP. @seanmcc-msft and @schoag-msft to comment further.

**Review by tanyasethi-msft — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
Yes but how common is that scenario? Disabling "secure by default" for something that I would think is the uncommon case seems a bit extreme, which is why I'm wondering is if there's another way to fix this.

**Comment by JeffreyRichter** [comment]
Well, I was always of the opinion that HTTP should be supported and not stopped by the SDK. Just like it would not be stopped by a customer using raw HTTP without an SDK. But, I do appreciate that this flies in the face of secure by default but then you might say that HTTP is not secure by default too but it is how it works. 

Also, shared key does not mean that the key itself goes over the wire in clear text. The client SDK uses the key to sign a string and this signed string goes over the wire in clear text with HTTP. Since it works this, it is not really a problem.

**Comment by jhendrixMSFT** [comment]
The clarification on how the string-to-sign works makes sense and was a missing piece of data.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
