### PR TITLE
Add go-redis authentication sample

### PR DESCRIPTION
**Pull request by chlowell**
Part of #17384

### CODE REVIEW

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by scottaddie** [comment]
@chlowell Would it make sense to create a samples directory for this stuff?

**Comment by chlowell** [comment]
What would you hope to improve by placing it somewhere else (not a rhetorical question 😄)? I wrote this to integrate with Go's built-in support for testable examples. Go will compile it as part of testing the library and place it in [this section of the package docs](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.8.0-beta.1#pkg-overview). Moving it outside `azidentity` would break that integration, so I don't see a clear benefit in doing that.

**Comment by scottaddie** [comment]
My reasoning is it feels strange to mix source for the library with sample code. I wasn't aware of the testable examples thing you mentioned, so I suppose what you have does make complete sense.

Once this PR merges, do we just need to update the Learn doc I mentioned in the issue?

**Review by RickWinter — APPROVED** [review]
This looks good.

Why don't we put this function onto/into Azure.Identity library. Azure Redis is an Azure product, rather than have everyone copy the code we could put the callback logic into the library. Then customers could write

```
func Example_redis() {
	credential, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		// TODO: handle error
	}
	client := redis.NewClient(&redis.Options{
		Addr:                       fmt.Sprintf("%s:6380", "TODO: redis host"),
		CredentialsProviderContext: azidentity.RedisCredentialProvider(credential),
		TLSConfig:                  &tls.Config{MinVersion: tls.VersionTLS12},
	})
	// TODO: use the client
	_ = client
}
```

**Comment by chlowell** [comment]
> My reasoning is it feels strange to mix source code for the library with sample code

Ah, yes, I agree it looks odd, especially because `azidentity` now appears to require `go-redis`. There are a couple conventions/language subtleties that apply here:
- `*_test.go` files aren't part of a published library i.e., applications can't reference their content
- Go recognizes dependencies used only in `*_test.go` files and installs them only when running tests

**Comment by chlowell** [comment]
> Why don't we put this function onto/into Azure.Identity library

I'm wary of doing that for a few reasons:
- we'd have to version this API with Redis's connection protocol
- I want to see evidence of widespread need before adding API
- different Redis clients have different interfaces; I imagine we'd always have some customers who must write adapter code

**Pull request merged**
