### PR TITLE
Enable spans in azkeys

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Regenerated code with inject-spans enabled.

- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by gracewilcox — APPROVED** [review]
LGTM

**Comment by jhendrixMSFT** [comment]
@benbp have you seen this?

**Comment by benbp** [comment]
go - azkeys - security - ci

**Comment by benbp** [comment]
@jhendrixMSFT @gracewilcox I think this is because of the pipeline rename [here](https://github.com/Azure/azure-sdk-for-go/pull/21652) but we need to re-generate some pipelines to point back to the new yaml files. That's why the triggers are failing.

**Comment by gracewilcox** [comment]
This is strange. I updated the pipelines to have the new name go - azkeys - ci, so it should be using that new name

**Comment by gracewilcox** [comment]
> @jhendrixMSFT @gracewilcox I think this is because of the pipeline rename [here](https://github.com/Azure/azure-sdk-for-go/pull/21652) but we need to re-generate some pipelines to point back to the new yaml files. That's why the triggers are failing.

Strange that we need to regenerate the pipelines. Thought I did it in my pull request, but might have been wrong.

**Comment by benbp** [comment]
@gracewilcox It's possible the generator won't forcibly change the location of the yaml files once it's been set. Let me see about manually changing it.

**Comment by benbp** [comment]
It's trickier because of how we determine the naming convention based on the file path, and the fact that there is already a pipeline from the older non-security yaml files that exists.

**Comment by gracewilcox** [comment]
Kk! I checked the live pipelines and at least they have been running correctly.

**Comment by jhendrixMSFT** [comment]
Can we delete the old pipelines for non-security KV stuffs now?

**Comment by gracewilcox** [comment]
> Can we delete the old pipelines for non-security KV stuffs now?

Deleted all the old pipelines. The proper pipeline should be go - azkeys - ci

**Pull request merged**
