### PR TITLE
ci: skip version pump for mgmt. plane sdk release

### PR DESCRIPTION
**Pull request by tadelesh**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by tadelesh** [comment]
For mgmt. plane SDK, we do not need the package version auto update. To prevent closing all the version pump PR, I just skip the job by default.

**Comment by weshaggard** [comment]
@tadelesh is the plan to update the versions as part of the code generation automation?

**Review by weshaggard — APPROVED** [review]
I'm ok with this as long as we have a good plan in the mgmt automation to correctly update the versions before releasing.

**Comment by tadelesh** [comment]
> @tadelesh is the plan to update the versions as part of the code generation automation?

Yes. As all the track2 mgmt. plane SDK are totally auto-generated, the release tool will do the version upgrade automatically when we prepare the release code and doc.

**Pull request merged**
