### PR TITLE
Enable CI for azqueue

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@weshaggard does this need to be merged before the automation can create the pipeline?  I'm guessing the answer is yes.

**Comment by weshaggard** [comment]
@jhendrixMSFT no I would expect the comment to correctly trigger this. I'm investigating.

**Comment by weshaggard** [comment]
@jhendrixMSFT I'm not sure why it didn't work when you triggered it but it did work when I triggred it.

**Pull request merged**
