### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Update changelog and glide dependencies.  Rename Acl to ACL to be golint
    clean.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@garimakhulbe @mcardosos PTAL, thanks!

**Comment by garimakhulbe** [comment]
@jhendrixMSFT Could you follow the steps I sent in mail and update go-autorest for changelog and tag it first? Because this will change its commit id.

**Comment by jhendrixMSFT** [comment]
@garimakhulbe Thanks for the instructions, PR updated.

**Comment by stack72** [comment]
Hi @garimakhulbe this is currently a blocked for me and would love to get it resolved today

**Comment by garimakhulbe** [comment]
Don't know how I missed it. LGTM. 

@jhendrixMSFT @mcardosos You can tag now. Just curious, Go files in PR are AutoRest generated. Right?

**Comment by garimakhulbe** [comment]
@jhendrixMSFT @mcardosos If its not AutoRest generated then we should not merge and fix it at generator. Thoughts?

**Comment by garimakhulbe** [comment]
@jhendrixMSFT we weren't sure on whether this PR is Autorest generated and user was waiting on this so @mcardosos  created a new one through AutoRest and merged that. Closing this now. Thanks for your effort.

**Pull request closed without merging**
