### PR TITLE
Add docs for committing/updating assets.json

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to module CHANGELOG.md are included.
- [ ] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go

### CODE REVIEW

**Review by benbp — APPROVED** [review]

**Comment by benbp** [comment]
@scbedd FYI

**Comment by jhendrixMSFT** [comment]
Let me know if this needs further embelishment.

**Comment by benbp** [comment]
It looks good to me @jhendrixMSFT

**Pull request merged**
