### PR TITLE
fix json model Path for Azure Data Lake Storage. Fix #16401

### LINKED ISSUE #16401: Wrong json model on Data Lake Storage "Path"
### Bug Report

- import path of package in question: github.com/Azure/azure-sdk-for-go/services/storage/datalake/2019-10-31/storagedatalake
- SDK version: 58.3.0
- output of `go version`: go version go1.17 linux/amd64

- What happened?
 While trying to list paths got json parse error
```
Error = 'json: cannot unmarshal string into Go struct field Path.paths.contentLength of type int64' JSON = '{"paths":[{"contentLength":"0","etag":"0x8D9B8C1E77A2CCF","group":"$superuser","isDirectory":"true","lastModified":"Mon, 06 Dec 2021 14:08:40 GMT","name":"vms/7e5ffad1-c24d-11e8-911f-c4b301c47c6b","owner":"$superuser","permissions":"rwxr-x---"},{"contentLength":"0","etag":"0x8D9B8C4BB9B08F6","group":"$superuser","isDirectory":"true","lastModified":"Mon, 06 Dec 2021 14:28:55 GMT","name":"vms/dd981f75-c6ed-11e8-bb55-c4b301c47c6b","owner":"$superuser","permissions":"rwxr-x---"},{"contentLength":"24","etag":"0x8D9B8CD715E87DE","group":"$superuser","lastModified":"Mon, 06 Dec 2021 15:31:15 GMT","name":"vms/last","owner":"$superuser","permissions":"rw-r-----"}]}
```

- What did you expect or want to happen?
 To get the list of paths from the api
- How can we reproduce it?
 Use PathClient.List
- Anything we should know about your environment.
Using linux and go 1.17, nothing special

### PR DESCRIPTION
**Pull request by asafg6**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Hi @asafg6 could you please run `gofmt` on your changed file? This is causing CI failures. Once you resolve this, I will merge your PR.

**Review by lirenhe — APPROVED** [review]

**Comment by lirenhe** [comment]
Thanks @asafg6 for your contribution.  The fix for this package will be released soon.

**Pull request merged**
