### PR TITLE
使用过程中遇到问题后的一些修改

### PR DESCRIPTION
**Pull request by jinxue-w**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] The PR targets the `latest` branch.
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] Apache v2 license headers are included in each file.
 
[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by jinxue-w** [comment]
> Can one of the admins verify this patch?

为什么会检查失败呢，我这是工作中遇到修改后可以用的，你们人工验证过吗

**Comment by ArcturusZhang** [comment]
Hi @jinxue-w thanks for contributing to Go SDK.
But unfortunately everything under the `services` directory in this SDK is auto-generated from the [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), therefore any changes to those code would be overridden in the next release.
The specs that generates the code you are attempting to change is [here](https://github.com/Azure/azure-rest-api-specs/blob/0cd0fca81547af948dae48bf905b71a45c7f7972/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-10-01/costmanagement.json#L1131)
Therefore I will close this PR, hope you would not mind.
As for the issue you met, I have seen others raised before (but I did not find the original issue). Could you please open an issue in this repo for this for us to track? Then I will try to inform this to the corresponding service team. Thanks!

**Comment by ArcturusZhang** [comment]
Oh well, I have found the related issue: https://github.com/Azure/azure-sdk-for-go/issues/8132
I will try to push the service team fix this. Sorry for the inconvenience!

**Comment by jinxue-w** [comment]
> Oh well, I have found the related issue: #8132
> I will try to push the service team fix this. Sorry for the inconvenience!

这个应就是之前我的问题，我之前提交了工单，和微软同学一起检查解决的，后来有遇到了其他问题，有了之前的经验就自己解决了，我的修改会比这个多了一些

**Pull request closed without merging**
