### PR TITLE
armstorageimportexport - clean up client constructors

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
We don't allow optional client constructor parameters for ARM. Use an autorest transform until the OpenAPI has been fixed.

- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to module CHANGELOG.md are included.
- [ ] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go

### CODE REVIEW

**Review by tadelesh — APPROVED** [review]
@jhendrixMSFT do you mean it is illegal to have optional client param for arm? There is another service with required client param: https://github.com/Azure/azure-sdk-for-go/blob/8166b03403f7d87203702589fb65ddf148611540/sdk/resourcemanager/apicenter/armapicenter/services_client.go#L36, it is legal?

**Comment by jhendrixMSFT** [comment]
The `*arm.ClientOptions` type is legal and expected.  In your example, `serviceName` looks to be required?

**Comment by jhendrixMSFT** [comment]
I wonder though, should `serviceName` actually be a client parameter?  It's almost always the wrong choice.

**Comment by tadelesh** [comment]
> I wonder though, should `serviceName` actually be a client parameter? It's almost always the wrong choice.

I'm also has such concern. Go just followed other languages. I'll try to confirm with service team.

**Pull request merged**
