### PR TITLE
Add doc links to fakes example

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by tadelesh — APPROVED** [review]

**Comment by tadelesh** [comment]
It seems relative links is not allowed.

**Comment by jhendrixMSFT** [comment]
@benbp it seems that using a `.` still isn't working for relative paths.  Is this something that can be fixed?

**Comment by benbp** [comment]
@jhendrixMSFT  IIRC we may have either an exception and/or cache process for relative links. I need to dig.

**Comment by jhendrixMSFT** [comment]
Switched to absolute links.  It would be great if relative links work in the future.

**Pull request merged**
