### PR TITLE
Deprecate azartifacts

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by chlowell** [comment]
Isn't this already done? https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/synapse/azartifacts?tab=versions

**Comment by jhendrixMSFT** [comment]
The retractions are for specific module versions.  This will deprecate the module as a whole.

**Review by RickWinter — COMMENTED** [review]
Thx for fixing

**Pull request merged**
