### PR TITLE
v37.0.0

### PR DESCRIPTION
**Pull request by ArcturusZhang**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] The PR targets the `latest` branch.
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] Apache v2 license headers are included in each file.
 
[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT I notice that in this update, the parameter order in `appplatform` has changed. 
Is there recently a change on autorest that could change this? I asked the service team that owns appplatform, there is no change on their swaggers.

**Comment by jhendrixMSFT** [comment]
The change in ordering is due to the following commit.
https://github.com/Azure/azure-rest-api-specs/commit/98c74125ced2106024ec5a837d882c56e46765f5#diff-b79a9f207fe92ed29a3d10963a8d9c38
The parameter changed from optional to required.  Optional parameters are always sequenced after required parameters, and since this is no longer required it's placed in sort-order.

**Comment by ArcturusZhang** [comment]
> The change in ordering is due to the following commit.
> [Azure/azure-rest-api-specs@98c7412#diff-b79a9f207fe92ed29a3d10963a8d9c38](https://github.com/Azure/azure-rest-api-specs/commit/98c74125ced2106024ec5a837d882c56e46765f5#diff-b79a9f207fe92ed29a3d10963a8d9c38)
> The parameter changed from optional to required. Optional parameters are always sequenced after required parameters, and since this is no longer required it's placed in sort-order.

I see. Actually currently, every parameters for this service is required and then the order of these parameters is same as the order they are defined, right? I just did a little experiment about this, which is saying so.
So I may need to ask the service team to alternate their order of parameters to make things right before i can release this major version.

**Comment by ArcturusZhang** [comment]
> The change in ordering is due to the following commit.
> [Azure/azure-rest-api-specs@98c7412#diff-b79a9f207fe92ed29a3d10963a8d9c38](https://github.com/Azure/azure-rest-api-specs/commit/98c74125ced2106024ec5a837d882c56e46765f5#diff-b79a9f207fe92ed29a3d10963a8d9c38)
> The parameter changed from optional to required. Optional parameters are always sequenced after required parameters, and since this is no longer required it's placed in sort-order.

I submitted a [pr](https://github.com/Azure/azure-rest-api-specs/pull/7874) in spec to fix this.

**Comment by ArcturusZhang** [comment]
The parameter order of appplatform has been fixed

**Comment by ArcturusZhang** [comment]
It seems all the problems in this major version release are fixed! I manually excluded those malformed swagger when generating this major release.
@jhendrixMSFT please have a look, thanks 🚀

**Comment by ArcturusZhang** [comment]
Hi @tombuildsstuff we have this SDK new version v37.0.0, and the issue with 32-bit compilation failure described [here](https://github.com/Azure/azure-rest-api-specs/pull/7847) should be resolved 🚀
Please have a look~

**Pull request merged**
