### PR TITLE
[azservicebus] Getting live tests working

### LINKED ISSUE #15714: [service-bus] Live testing
Live testing needs to be setup - mostly just translating the older .tf file that had the resources into a standard ARM template.

### PR DESCRIPTION
**Pull request by richardpark-msft**
Grabbed the test-resources.json from the JS SDK, made a small adjustment to load up the right credential type.

Fixes #15714

### CODE REVIEW

**Comment by richardpark-msft** [comment]
I didn't use bicep @benbp, which might be a strike against me.

**Review by benbp — APPROVED** [review]

**Pull request merged**
