### PR TITLE
Address unintentional field and structure renaming, #231

### PR DESCRIPTION
**Pull request by brendandixon**
This addresses the unintentional structure renaming which occurred in last auto-generated code. It addresses #231.

Signed-off-by: Brendan Dixon <brendand@microsoft.com>

### CODE REVIEW

**Comment by brendandixon** [comment]
@ahmetalpbalkan @paulmey Do you mind if I merge this? It corrects the renaming issues that crept in with the last PR.

**Comment by ahmetalpbalkan** [comment]
Lgtm

**Comment by axw** [comment]
@brendandixon Thanks, this does fix the issues I noted in #231. The remaining name changes seem fine (ResourceGroup, and SecurityRuleProtocol{TCP,UDP}).

**Comment by brendandixon** [comment]
@axw Glad to hear it! We'll merge to master soon.

**Pull request merged**
