### PR TITLE
Major version release v49.0.0

### PR DESCRIPTION
**Pull request by ArcturusZhang**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] Apache v2 license headers are included in each file.
 
[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
Unclear why `go vet` is failing, can you please investigate?

**Comment by jhendrixMSFT** [comment]
Fixes https://github.com/Azure/azure-sdk-for-go/issues/13641

**Comment by ArcturusZhang** [comment]
The operationalinsights/2019-08-01-preview still has a "nextlink" issue. I will go and check if there is an issue there (I remember I once went into this before and opened one issue about this).
I removed the problematic pacakge in this release (it is a new package, therefore no impact)

**Comment by ArcturusZhang** [comment]
Issue link here: https://github.com/Azure/azure-rest-api-specs/issues/11420
I will open another PR to swagger to remove this tag from the readme since it is problematic

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT I have fixed all the issues, please have a look, thanks

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
