### PR TITLE
Alpha of ARM packages

### PR DESCRIPTION
**Pull request by brendandixon**
This pull request adds the alpha version of the Azure Resource Manager packages. The README.md within the included examples folder provides usage detail.

Signed-off-by: Brendan Dixon <brendand@microsoft.com>

### CODE REVIEW

**Comment by brendandixon** [comment]
@ahmetalpbalkan I'd like to merge this today. The contained README.md gives pretty good detail. Much more to come!

**Comment by ahmetalpbalkan** [comment]
@brendandixon  Looks reasonable, feel free to merge. One thing I can see right away is maybe we should move README from arm/examples to arm so that from github, whoever clicks on arm folder can see it directly.

**Comment by ahmetalpbalkan** [comment]
oh actually can you also update .travis.yml to compile and check-gofmt of arm/... as well? Right now I'm not sure if the CI is conclusive.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Agreed. I'll move the README.md up one. CI may be failing because I'm merging a branch vs. a PR from master. I'll take a look.

**Comment by brendandixon** [comment]
@ahmetalpbalkan I'm going to close and issue a new PR directly from / to master.

**Comment by ahmetalpbalkan** [comment]
@brendandixon Please do not open and close PRs all the time, it's being hard for me to keep record. consider reopening this.

image

It's failing because in the code we probably have references such as `import "github.com/azure/repo/not-yet-merged-directory"`. I don't know how we solved this initially but the command failing is `go get -t ./...` which is supposed to fetch all the dependencies.

It might be a first-time bootstrapping problem, in that case we can just merge and next PRs wont have this problem.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Sorry to confuse you. I'm used to having single issue PRs.

I agree this is likely a bootstrapping. I'll do something...

**Comment by brendandixon** [comment]
@ahmetalpbalkan Re-opening.

**Pull request closed without merging**
