### PR TITLE
Adding Multi-API Version support packages.

### PR DESCRIPTION
**Pull request by marstr**
This is a set of packages generated by the most recent `generator.exe` which have explicit support for every API Version that a Service supports.

Currently there are a few notable missing packages, but they will all be added in before these changes hit master:
edit: At this point, recovery services and all of its children are the only ones that we ship today that aren't present in this PR.

 - azsadmin
 - batchai
 - cognitive services data-plane packages
 - machine learning compute
 - ~~marketplace ordering~~ edit: added in ff8c2c2
 - ~~operations management~~ edit: added in c80ca3a
 - recovery services
 - recovery services backup
 - recovery services site recovery
 - ~~resource health~~ edit: this was added in 14f105a
 - ~~resources~~ edit: this was added in a5ce301
 - ~~service map~~ edit: this was added in e8dd531a
 - ~~sql~~ edit: this was added in c394fb4
 - ~~traffic manager~~ edit: this was added in c2dc1c44
 - ~~web~~ edit: this was added in 5f51c6a

A few packages broke our generator, and I've manually deleted them. Those are: 
 - compute 2015-06-15
 - network 2015-05-01-preview
 - network 2015-06-15

These packages are a direct result of the changes seen in https://github.com/Azure/azure-rest-api-specs/pull/1787

### CODE REVIEW

**Comment by marstr** [comment]
To review, I'd recommend a `git checkout` out on my fork's `dev` branch and playing with it.

**Comment by mcardosos** [comment]
`cosmos-db` has package `documentdb` inside, is that intentional?

**Comment by mcardosos** [comment]
Another question, this would not replace the arm folder? For breaking changes reasons

**Comment by mcardosos** [comment]
Datalake Analytics management package is missing.

**Comment by mcardosos** [comment]
Not a big fan of `machine_learning` folder having an underscore

**Comment by mcardosos** [comment]
Question, are you planning to generate a `latest` profile that works the same as our current `arm` folder?

**Comment by mcardosos** [comment]
`billing` is missing the `mgmt` folder

**Comment by mcardosos** [comment]
There are some dataplane SDKs that we are not generatin right now, `monitor`, `search`, `servicefabric`

**Comment by marstr** [comment]
> @mcardosos says:
> `cosmos-db` has package `documentdb` inside, is that intentional?

Yep! I was just trying to match their Swagger declarations found here: [Azure/azure-rest-api-specs/specification/cosmos-db/resource-manager/Microsoft.DocumentDB](https://github.com/Azure/azure-rest-api-specs/tree/945456b00628467799654c6d7ddfe52a34c717d8/specification/cosmos-db/resource-manager/Microsoft.DocumentDB)

**Comment by marstr** [comment]
> @mcardosos says:
> Another question, this would not replace the arm folder? For breaking changes reasons

Correct, today it would not replace it, and we'd release that as `v11.2.0-beta` but starting in `v12` we'd mark everything in the arm directory as deprecated.

**Comment by marstr** [comment]
> @mcardosos says
Question, are you planning to generate a `latest` profile that works the same as our current `arm` folder?

Yes, at least in some capacity. However, I'm going to be sending a separe profile PR after this one is merged into `dev`.

**Comment by marstr** [comment]
> @mcardosos says:
There are some dataplane SDKs that we are not generatin right now, monitor, search, servicefabric

🤐 This was deliberate on my part.

**Comment by marstr** [comment]
> @mcardosos says:
Not a big fan of machine_learning folder having an underscore

I'll take it out then. No biggie.

**Pull request merged**
