### PR TITLE
[backport:master] add README

### PR DESCRIPTION
**Pull request by joshgav**
backport of https://github.com/Azure/azure-sdk-for-go/pull/892 to master

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@joshgav Presumably this is the same change from the dev branch, if so can we just cherry-pick that commit so that we don't introduce a merge conflict when we merge dev into master?

**Comment by joshgav** [comment]
this is in fact a cherry-pick of https://github.com/Azure/azure-sdk-for-go/commit/4494f695920ad731d9b976c8fe5037695798342f :smile:

**Comment by jhendrixMSFT** [comment]
Awesome, I wonder if we can forego merging this through github and just push the commit to master, @marstr what do you think?

**Comment by joshgav** [comment]
pushed cherry-picked commit to master in https://github.com/Azure/azure-sdk-for-go/commit/a49674fdba11173ce3bc934d020634e3366464de as discussed offline with @jhendrixMSFT. Thanks!

**Comment by marstr** [comment]
Just pushing instead of using the GitHub interface gets my stamp of approval. :) Though the way things turned out, the commit that is being used by people with `go get` and people using `dep` has deviated. It's not a big deal, but still something I aim to avoid.

**Pull request merged**
