### PR TITLE
chore: Update custom_client.go to enable insecure credential with HTTP

### PR DESCRIPTION
**Pull request by ukrocks007**
This PR enables `InsecureAllowCredentialWithHTTP` option for ai sdk custom_client

- [x] The purpose of this PR is explained in this or a referenced issue.
- [x] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [x] Updates to module CHANGELOG.md are included.
- [x] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go

### CODE REVIEW

**Comment by ukrocks007** [comment]
@microsoft-github-policy-service agree [company="BoxyHQ"]

**Review by richardpark-msft — APPROVED** [review]

**Comment by richardpark-msft** [comment]
@ukrocks007, thank you for your contribution! I am interested - when do you disable the secure auth? The cases I'm aware of - using a proxy, using some form of "emulator/pass through" (usually homegrown).

**Comment by ukrocks007** [comment]
> @ukrocks007, thank you for your contribution! I am interested - when do you disable the secure auth? The cases I'm aware of - using a proxy, using some form of "emulator/pass through" (usually homegrown). 

It is for a proxy solution, and the endpoint is open ended so it is possible that endpoint can be http.

**Pull request merged**
