### PR TITLE
Make installing the guest agent configurable for VMImages

### PR DESCRIPTION
**Pull request by svanharmelen**
I know this would probably go into an option struct, but I think that should be another refactor. So for now just added a `bool`.

And while touching this file I also made it’s 100+ lines a little shorter which makes reviewing on GH a lot nicer.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
Thanks! Tests are failing.

**Comment by svanharmelen** [comment]
Argh, sorry about that! Tests updated now as well...

**Comment by ahmetalpbalkan** [comment]
LGTM, @paulmey please review and merge.

**Comment by paulmey** [comment]
LGTMToo

**Pull request merged**
