### PR TITLE
v12.4.0-beta

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Added API version 2017-12-01 for the compute package.

Thanks you for your contribution to the Azure-SDK-for-Go! We will triage and review it as quickly as we can.

As part of your submission, please make sure that you can make the following assertions:

 - [ ] I'm not making changes to Auto-Generated files which will just get erased next time there's a release.
   - If that's what you want to do, consider making a contribution here: https://github.com/Azure/autorest.go
 - [ ] I've tested my changes, adding unit tests where applicable.
 - [ ] I've added Apache 2.0 Headers to the top of any new source files.
 - [ ] I'm submitting this PR to the `dev` branch, or I'm fixing a bug that warrants its own release and I'm targeting the `master` branch.
 - [ ] If I'm targeting the `master` branch, I've also added a note to [CHANGELOG.md](https://github.com/Azure/azure-sdk-for-go/blob/master/README.md).
 - [ ] I've mentioned any relevant open issues in this PR, making clear the context for the contribution.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
Fixes https://github.com/Azure/azure-sdk-for-go/issues/944.

**Comment by vladbarosan** [comment]
@jhendrixMSFT  Don't we need to regenerate the profiles also ?

**Comment by jhendrixMSFT** [comment]
Yes you're right good catch.

**Comment by jhendrixMSFT** [comment]
@vladbarosan Actually I would like to defer on that for now.  We didn't do it for v12.3.0 so it's going to bring in a lot more changes than just this API revision.

**Comment by vladbarosan** [comment]
@jhendrixMSFT ah too bad. I am host scared that people will be confused for about why latest is not poiting to latest.

**Comment by jhendrixMSFT** [comment]
Let's get the profiles updated for everything in a v12.4.1 release.

**Comment by vladbarosan** [comment]
@jhendrixMSFT sounds good your proposal

**Pull request merged**
