### PR TITLE
Remove locale in link

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Per guidelines in https://aka.ms/azsdk/guideline/links

- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@benbp is it possible to set up a pipeline for docs that just performs link verification and nothing else?  This break was noticed after-the-fact due to lack of CI.

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1588275&view=results

**Comment by benbp** [comment]
@jhendrixMSFT let me look into it. I'm vaguely recalling that we had to disable CI link verification due to mgmt plane onboarding chicken or egg problems? Otherwise I would have expected this same pipeline that's failing to now to have failed as a PR gate.

**Comment by tadelesh** [comment]
> Looks like it was overridden, probably due to CI hanging like it was for me this morning.
> 
> #17763

I override the check because of the chicken or egg problem for the new created doc. Sorry for miss this link problem. It is weird in my region; the URL works fine with `en-us`.

**Review by tadelesh — APPROVED** [review]

**Comment by tadelesh** [comment]
> > > Looks like it was overridden, probably due to CI hanging like it was for me this morning.
> > > #17763
> > 
> > 
> > I override the check because of the chicken or egg problem for the new created doc. Sorry for miss this link problem. It is weird in my region; the URL works fine with `en-us`.
> 
> @tadelesh we explicitly disallow region/language links in favor of the non-region specific URLs which is probably why it failed.

Got it. Thanks.

**Pull request merged**
