### PR TITLE
[Identity] fixing lint step for azidentity

### PR DESCRIPTION
**Pull request by seankane-msft**
Fixes lint step. For now skipping `golangci-lint` step on the four issues that are flagged by the linter

### CODE REVIEW

**Comment by chamons** [comment]
Do we want to issue this for fixing later, or are these false positives?

**Comment by seankane-msft** [comment]
> Do we want to issue this for fixing later, or are these false positives?

@chamons [issue for this](https://github.com/Azure/azure-sdk-for-go/issues/15110)

**Comment by chamons** [comment]
👍  - Please link it in the commit when you merge this.

**Review by catalinaperalta — APPROVED** [review]

**Pull request merged**
