### PR TITLE
Add DragonFlyBSD in azfile

### PR DESCRIPTION
**Pull request by tuxillo**
Since DragonFlyBSD is already listed as supported in ed939da099c54c2ae8708bfa0316021d081f36fe , add it to azfile too.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by souravgupta-msft — APPROVED** [review]

**Comment by souravgupta-msft** [comment]
@microsoft-github-policy-service agree

**Comment by tuxillo** [comment]
@microsoft-github-policy-service agree

**Review by gapra-msft — APPROVED** [review]

**Pull request merged**
