### PR TITLE
Refactor `pkgchk` tool and expose some api

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Refactor the tool and expose some API so that we could reuse the pkgchk logic in other tools, especially the `generator` tool to check the `output-folder` correctness in a swagger PR

- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] Apache v2 license headers are included in each file.
 
[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Hey @jhendrixMSFT could you please take a review on this PR?

**Comment by jhendrixMSFT** [comment]
This just makes some content public, it doesn't change any behavior?

**Comment by ArcturusZhang** [comment]
> This just makes some content public, it doesn't change any behavior?

Making things public and some refactor, no behavioral change except the path of a package will no longer start with `/` (see the changes in `exceptions.txt`

**Comment by ArcturusZhang** [comment]
Hey @jhendrixMSFT any update?

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
