### PR TITLE
Fix struct ordering to satify the API

### PR DESCRIPTION
**Pull request by svanharmelen**
Fixes issue #153

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@svanharmelen can you please squash into one commit and fix the test breaks?

**Comment by svanharmelen** [comment]
Sure... Just don't see what the actual problem is. It looks like the command fails and directly after that is looks to pass:

image

So any pointers what the actual problem is here?

**Comment by ahmetalpbalkan** [comment]
so the gofmt has edited these two files because they were not correctly formatted.

**Comment by svanharmelen** [comment]
@ahmetalpbalkan check, thanks... Only thing I can see is an additional newline on the last line of both files. Removing those fixed it. Will squash again...

**Comment by ahmetalpbalkan** [comment]
lgtm

**Pull request merged**
