### PR TITLE
Regenerated filesystem and updated dependencies

### PR DESCRIPTION
**Pull request by mcardosos**

### CODE REVIEW

**Comment by mcardosos** [comment]
@garimakhulbe

**Comment by garimakhulbe** [comment]
LGTM. Tag once build is green.

**Comment by garimakhulbe** [comment]
Please tag and release the new version.

**Comment by garimakhulbe** [comment]
@stack72 All set for v5.0.0. 
@mcardosos @jhendrixMSFT Thank you.

**Pull request merged**
