### PR TITLE
Updated DNS to latest Swager

### PR DESCRIPTION
**Pull request by brendandixon**
This should address #260.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@brendandixon looks like you dropped gocheck from vendored dependencies. Intentional?

**Comment by brendandixon** [comment]
Nope. I wonder how that happened...

**Comment by brendandixon** [comment]
Actually, it seems I corrected that mistake. It should be there now.

**Comment by brendandixon** [comment]
Ok to merge? This addresses (we hope) #260. It is intended to update *only* the arm/dns client.

**Comment by ahmetalpbalkan** [comment]
lgtm

**Pull request merged**
