### PR TITLE
Updating notification for Compute

### PR DESCRIPTION
**Pull request by Drewm3**
- [x] The purpose of this PR is explained in this or a referenced issue.
- [x] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [x] Tests are included and/or updated for code changes.
- [x] Updates to [CHANGELOG.md][] are included.
- [x] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by Drewm3** [comment]
@jsquire / @benbp / @RickWinter / @jhendrixMSFT / @ronniegeraghty, is there anything else that you need from me before this can be approved and merged?

**Review by RickWinter — APPROVED** [review]

**Comment by Drewm3** [comment]
@RickWinter, is there anything else that is needed here?

**Pull request merged**
