### PR TITLE
Prepare azidentity v1.3.0-beta.2 for release

### PR DESCRIPTION
**Pull request by chlowell**

### CODE REVIEW

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by tareqhs** [comment]
hi @chlowell when is azidentity 1.3.0 planned to be released?
we need this for using workload identities via env (https://github.com/Azure/azure-sdk-for-go/pull/19503)

**Comment by chlowell** [comment]
We plan to release a stable 1.3.0 in early April. In the meantime, please try the beta and open an issue if you find any problems.

**Comment by tareqhs** [comment]
hi @chlowell , any update on the release schedule for azidentity 1.3.0?

**Comment by chlowell** [comment]
No, still planning to publish tomorrow.

**Pull request merged**
