### PR TITLE
[Release] sdk/resourcemanager/managednetworkfabric/armmanagednetworkfabric/0.1.0

### PR DESCRIPTION
**Pull request by Alancere**
https://github.com/Azure/sdk-release-request/issues/4253

### CODE REVIEW

**Comment by Alancere** [comment]
module-name approved: https://github.com/Azure/azure-sdk/issues/5428#issuecomment-1416125581

**Review by tadelesh — COMMENTED** [review]
Please add live test according to JS's test cases.

**Comment by Alancere** [comment]
The resource type could not be found in the namespace 'Microsoft.ManagedNetworkFabric' for api version '2023-02-01-preview'.

**Review by tadelesh — APPROVED** [review]
Add live test before GA.

**Pull request merged**
