### PR TITLE
Migrate license to MIT

### PR DESCRIPTION
**Pull request by qt-luigi**
Update a license to MIT at a line of license headers check.

### CODE REVIEW

**Comment by qt-luigi** [comment]
Thanks for merging me! q@w@p

**Comment by qt-luigi** [comment]
@ArcturusZhang "Apache License" exists in other files yet. I cannot fix it because these files are .go file. Please check it and fix it.

% find . -type f | xargs grep "Apache License"
./tools/pkgchk/track1/verifiers.go:// Licensed under the Apache License, Version 2.0 (the "License");
./tools/pkgchk/track1/packages.go:// Licensed under the Apache License, Version 2.0 (the "License");
./tools/pkgchk/track1/packages_test.go:// Licensed under the Apache License, Version 2.0 (the "License");
./tools/pkgchk/packages/verifiers.go:// Licensed under the Apache License, Version 2.0 (the "License");
./tools/pkgchk/packages/packages.go:// Licensed under the Apache License, Version 2.0 (the "License");
./doc.go:// Licensed under the Apache License, Version 2.0 (the "License");
./version/version.go:// Licensed under the Apache License, Version 2.0 (the "License");

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang "Apache License" exists in other files yet. I cannot fix it because these files are .go file. Please check it and fix it.
> 
> % find . -type f | xargs grep "Apache License"
> ./tools/pkgchk/track1/verifiers.go:// Licensed under the Apache License, Version 2.0 (the "License");
> ./tools/pkgchk/track1/packages.go:// Licensed under the Apache License, Version 2.0 (the "License");
> ./tools/pkgchk/track1/packages_test.go:// Licensed under the Apache License, Version 2.0 (the "License");
> ./tools/pkgchk/packages/verifiers.go:// Licensed under the Apache License, Version 2.0 (the "License");
> ./tools/pkgchk/packages/packages.go:// Licensed under the Apache License, Version 2.0 (the "License");
> ./doc.go:// Licensed under the Apache License, Version 2.0 (the "License");
> ./version/version.go:// Licensed under the Apache License, Version 2.0 (the "License");

Sorry I did not notice this earlier - but these have already been changed. Thank you!

**Comment by qt-luigi** [comment]
Thanks for checking these files! I also checked that ./tools/pkgchk/* files have fixed to MIT. If you O.K., One more time, Please check next .go files. I see that these files do not fixed yet. It is on a master brunch.

azure-sdk-for-go/doc.go at master · Azure/azure-sdk-for-go · GitHub
https://github.com/Azure/azure-sdk-for-go/blob/master/doc.go

azure-sdk-for-go/version.go at master · Azure/azure-sdk-for-go · GitHub
https://github.com/Azure/azure-sdk-for-go/blob/master/version/version.go

**Pull request merged**
