### PR TITLE
Add container service and readded NewxxClientBaseURI

### PR DESCRIPTION
**Pull request by garimakhulbe**
* Added container service code in compute package. 
* Readded NewxxClientBaseURI method.
* version change 3.0.0-beta -> 3.1.0-beta
* go-autorest version v7.0.7.

### CODE REVIEW

**Comment by garimakhulbe** [comment]
This will fix #356, #345.

**Comment by colemickens** [comment]
Just curious, why `3.1.1-beta` rather than `3.1.0-beta`?

**Comment by garimakhulbe** [comment]
To reflect go-autorest recent fixes.

**Comment by ahmetalpbalkan** [comment]
LGTM as well, CI failing due to gofmt issues in containerservice code

**Comment by garimakhulbe** [comment]
Thanks.

**Pull request merged**
