### PR TITLE
Fixing the hostedservice

### PR DESCRIPTION
**Pull request by svanharmelen**
This one is also broken, so just restoring services here...

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@svanharmelen thanks for noticing! I made all those changes w/o running the integration tests. @paulmey can we please run those sometime?

**Comment by svanharmelen** [comment]
@ahmetalpbalkan would be nice if you can merge this relatively simple fix to get it off the table and working again...

**Comment by paulmey** [comment]
LGTM, integration tests are running and the breaks are showing up in your email... :-)

**Comment by svanharmelen** [comment]
@paulmey thx!

**Pull request merged**
