### PR TITLE
[Release] sdk/resourcemanager/network/armnetwork/3.0.0

### PR DESCRIPTION
**Pull request by Alancere**
https://github.com/Azure/sdk-release-request/issues/4140

### CODE REVIEW

**Comment by MikhailTryakhov** [comment]
LGTM

**Comment by Alancere** [comment]
The breaking changes are introduced and approved in [this PR](https://github.com/Azure/azure-rest-api-specs/pull/23652).

and https://github.com/Azure/azure-rest-api-specs/pull/23738

**Comment by MikhailTryakhov** [comment]
Yes, this breaking change was approved by Jeffrey Richter's team

**Comment by raych1** [comment]
> Yes, this breaking change was approved by Jeffrey Richter's team

There're gaps there after I double checked.

@JeffreyRichter , can you approve the [swagger breaking change](https://github.com/Azure/azure-rest-api-specs/pull/23738#issuecomment-1524401113)?

**Comment by raych1** [comment]
Thanks @JeffreyRichter for approving the swagger PR. Can you please approve this PR by adding label of `Approved Major Version`?

**Review by tadelesh — APPROVED** [review]

**Pull request merged**
