### PR TITLE
[AzDatalake] Pipelines + cleanup

### PR DESCRIPTION
**Pull request by tasherif-msft**
TODO:
figure out unmarshaljson issue

### CODE REVIEW

**Review by vibhansa-msft — APPROVED** [review]

**Comment by benbp** [comment]
Is this copied over from net? I know in net the arm template is kind of a parent template for all their services, so it deploys everything. In go that's not the case, so we shouldn't be deploying all these extra resources in the template included here unless necessary. Similarly, I don't know if the go tests will require anything set up in https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/test-resources-post.ps1 or not?

**Pull request merged**
