### PR TITLE
Unexport HTTP headers to reduce public surface area

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by richardpark-msft — APPROVED** [review]
Looks good - private and a much smaller subset. Can't ask for much more :)

**Review by seankane-msft — APPROVED** [review]

**Review by catalinaperalta — APPROVED** [review]
LGTM. Although when I saw this, I thought maybe this could be put in the internal module so that the other libs could still use them and avoid declaring the same consts in different mods. Not sure if there would be any problem with that though. Also maybe it's too much work just for the header consts and the the benefit is really small.

**Comment by jhendrixMSFT** [comment]
It's not a bad idea, my only complaint is that it gets in the way.  i.e. when I'm doing some work in `azcore` I need to first add my constant(s) to `internal`, PR and commit, then update the dependency and move on.

Since this is all internal, if this does prove to be problematic in the future we can update it later without any impact to customers.

**Comment by catalinaperalta** [comment]
I see your point. If it's going to slow things down, then it's better this way for now. `azidentity` will need to be updated to not depend on these exported headers then, when updating to the latest `azcore`.

**Comment by jhendrixMSFT** [comment]
Agreed, and I think there will be a few more breaking changes from last week's review of `azcore` so we don't have to tag this right now.

**Comment by jhendrixMSFT** [comment]
Fixes https://github.com/Azure/azure-sdk-for-go/issues/15047

**Pull request merged**
