### PR TITLE
Use sdk/internal credential factory in messaging tests

### PR DESCRIPTION
**Pull request by chlowell**

### CODE REVIEW

**Comment by chlowell** [comment]
@richardpark-msft looks like azeventgrid - basic can't pass because most of the coverage comes from examples that don't run in playback?

**Comment by richardpark-msft** [comment]
> @richardpark-msft looks like azeventgrid - basic can't pass because most of the coverage comes from examples that don't run in playback?

Let me see what's going on there. If I fix something you want me to push to your branch?

**Comment by chlowell** [comment]
Sure, push whatever you like.

**Comment by richardpark-msft** [comment]
> Sure, push whatever you like.

I did a separate PR which went into main, so I just synced up. We should be good now (tests will pass because we have a whitespace change that still requires azeventgrid to run!).

**Review by jhendrixMSFT — APPROVED** [review]

**Review by RickWinter — APPROVED** [review]

**Pull request merged**
