### PR TITLE
Fix bug: Binary data is not properly encoded.

### PR DESCRIPTION
**Pull request by shiweiz**
Binary data should be encoded using base64.

### CODE REVIEW

**Comment by yuwaMSFT2** [comment]
@marstr @sajayantony @mcardosos @sivagms

**Comment by jhendrixMSFT** [comment]
@shiweiz sorry for the delay.  Can you please rebase this PR against the dev branch and fix the test failures?

**Comment by shiweiz** [comment]
@jhendrixMSFT Rebased this PR against the dev branch with the test failures auto fixed.

**Comment by jhendrixMSFT** [comment]
@shiweiz This is closer but is pulling in changes from master which we don't want to do.  I see your PR is originating from your fork of master, it might be better at this point to create a tracking branch for dev, port your change to dev, close this PR then open a new one from your fork of dev.  Tag me in the PR and I'll review it.

**Pull request closed without merging**
