### PR TITLE
Release v67.0.0 1665469788

### PR DESCRIPTION
**Pull request by Alancere**

### CODE REVIEW

**Review by tadelesh — APPROVED** [review]

**Comment by tadelesh** [comment]
Override check-enforcer for link check failure.

**Comment by benbp** [comment]
> @benbp before I merge this, do you want to take a look to see why check-enforcer is stuck?

@jhendrixMSFT go ahead and merge/override. It's stuck because it was open before I did the transition and has an old check enforcer check status pending. Since I disabled that check, it will never post success which is blocking the new check enforcer. I couldn't think of a great way to avoid this for a small subset of PRs but it shouldn't happen for any new PRs.

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@benbp for some reason the checkbox to enable admin to merge is missing on this PR.

**Comment by benbp** [comment]
> @benbp for some reason the checkbox to enable admin to merge is missing on this PR.

@jhendrixMSFT oh looks like this is a PR against the `legacy` branch, which I missed updating with the new rules. Let me switch it.

**Comment by jhendrixMSFT** [comment]
Thanks, I missed that too.

**Pull request merged**
