### PR TITLE
[azservicebus] Ignore the leading XMLNS for properties in subscription rules

### LINKED ISSUE #18785: [azservicebus] NewListRulesPager not working with Custom Properties in Correlation Filter
### Bug Report

NewListRulesPager not working with Custom Properties in Correlation Filter

- SDK version - github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus v1.0.2
- output of `go version` - go version go1.18.1 linux/amd64

- What happened?
listRulesPager.NextPage(ctx) gives below error when the rule filter is of type Correlation filter and contains Custom Properties.
Error: type d5p1:string of parameter check is not a handled type for SQL parameters

- What did you expect or want to happen?
NewListRulesPager  should not return error.
- How can we reproduce it?
Create a Rule on Subscription with filter of type Correlation filter and add Custom field in it. 
Try to fetch the Rule using NewListRulesPager
image

### PR DESCRIPTION
**Pull request by richardpark-msft**
The individual properties for a rule in Service Bus come with an XML ns prefix. We don't actually care about this as we're just trying to figure out what the assigned type is (string, int, etc..) so this just strips out the prefix.

Fixes #18785

### CODE REVIEW

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by richardpark-msft** [comment]
(had to go 1.19 gofmt)

**Comment by richardpark-msft** [comment]
The CI pipeline seems to be having issues unrelated to tests or code (it's failing to upload an artifact, but it's CI).

Bypassing - live tests and other CI pipelines have passed

**Pull request merged**
