### PR TITLE
Move test recordings under the testdata directory

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
This will omit megabytes of test assets from the module.
Updates test setup and teardown to use the latest APIs which allow
specifying the recordings directory.
Sanitized parts of the recordings to make the diffs less noisy. More
work is needed though.

Fixes https://github.com/Azure/azure-sdk-for-go/issues/17943

### CODE REVIEW

**Comment by mohsha-msft** [comment]
There are changes required in the test framework 
1. To move the test files in their respected packages and then 
2. Moving recordings to testdata/
3. Upgrade testing infra to take recording path insead of default path "recording/Test/testname"

But I realised it would need more time and seperate efforts.

**Comment by jhendrixMSFT** [comment]
Unfortunately, there are two sets of APIs in the test framework.  The original ones, which `azblob` is currently using, and updated ones which are introduced in this PR.  The updated ones let you specify the location and most of the tests are working.  I need to tweak the sanitization a bit more to fix the remaining tests.  I'll have this resolved today.

**Comment by jhendrixMSFT** [comment]
The problem was freezing the time stamps as this broke tests that use conditionals (e.g. `if-modified-since`).  I reverted that part of the change for now.

**Review by mohsha-msft — APPROVED** [review]
:shipit:

**Pull request merged**
