### PR TITLE
[azblob][sas] Fix SignWithSharedKey if stored access policy is used  @stotz89

### PR DESCRIPTION
**Pull request by stotz89**
This PR will fix https://github.com/Azure/azure-sdk-for-go/issues/21229

In addition it adds non-existing unit tests for the fixed method.

### CODE REVIEW

**Comment by stotz89** [comment]
@microsoft-github-policy-service agree company="SAP"

**Review by souravgupta-msft — APPROVED** [review]

**Review by vibhansa-msft — APPROVED** [review]

**Pull request merged**
