### PR TITLE
rename profile module

### PR DESCRIPTION
**Pull request by tadelesh**
Since the previous module name collides with the semantic versioning, we decide to rename `v20200901` to `p20200901`.

### CODE REVIEW

**Comment by tadelesh** [comment]
@jhendrixMSFT Could you help to review and approve?

**Review by jhendrixMSFT — APPROVED** [review]
Looks like the `ModuleName` constant's value doesn't match the name of the module.  Is that intentional?

**Comment by tadelesh** [comment]
> Looks like the `ModuleName` constant's value doesn't match the name of the module. Is that intentional?

Good catch. I've consolidated it.

**Pull request merged**
