### PR TITLE
Add support for ResourceGUID property

### PR DESCRIPTION
**Pull request by rayterrill**
https://github.com/hashicorp/terraform-provider-azurerm/issues/17011

- [x] The purpose of this PR is explained in this or a referenced issue.
- [x] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][x].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [x] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by tadelesh** [comment]
@rayterrill Our SDK is auto generated by service swagger definition. According to the [spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/privateEndpoint.json#L678), `resourceGuid` is not defined. Meanwhile, you are trying to change our previous SDK which has already been deprecated. After the service team fix the swagger, we could only update our new SDK which module path is `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork`.

**Comment by rayterrill** [comment]
@tadelesh is there an issue to get the swagger updated so the SDK can be regenerated with resourceGuid?

**Comment by tadelesh** [comment]
> @tadelesh Chenjie Shi FTE is there an issue to get the swagger updated so the SDK can be regenerated with resourceGuid?

It seems not currently. Could you help to raise an issue in the swagger [repo](https://github.com/Azure/azure-rest-api-specs/issues)?

**Comment by rayterrill** [comment]
@tadelesh Looks like there is at least one already, but it's been open since May: https://github.com/Azure/azure-rest-api-specs/issues/19111. Potentially this one as well: https://github.com/Azure/azure-rest-api-specs/issues/16693.

**Comment by rayterrill** [comment]
@tadelesh we ended up using the azurerm terraform provider instead - it's a bummer that the main terraform-provider-azurerm uses the deprecated SDK (https://github.com/hashicorp/terraform-provider-azurerm/blob/c4ff420ccd94b60ce9b99be9ab5a67a35adc9fd0/internal/services/network/private_endpoint_resource.go#L11) - that's what let me down this path.

**Comment by tadelesh** [comment]
I understand. The reason that terraform does not migrate to new SDK immediately is a long story. We are still discussing about it continuously. For this issue, the first thing we could do is to fix the swagger. As said in this [issue](https://github.com/Azure/azure-rest-api-specs/issues/19111#issuecomment-1282272934), we have already pushed the service team to look into it. I'll follow up with it.

**Pull request closed without merging**
