### PR TITLE
Container instance

### PR DESCRIPTION
**Pull request by mcardosos**
PTAL
@jhendrixMSFT @marstr

### CODE REVIEW

**Comment by kirankumarbv** [comment]
Hey,
You have changed the file /root/godep/src/github.com/Azure/azure-sdk-for-go/datalake-store/filesystem/version.go to have package datalakestore instead of package filesystem, but client.go still has package filesystem which caused this error in my system.
can't load package: package github.com/Azure/azure-sdk-for-go/datalake-store/filesystem: found packages filesystem (client.go) and datalakestore (version.go) in github.com/Azure/azure-sdk-for-go/datalake-store/filesystem

**Comment by mcardosos** [comment]
Hello @kirankumarbv !
Thanks for reporting this issue! I have just fixed it and released a new patch :)

**Comment by kirankumarbv** [comment]
You are welcome. 
I had a question about the sdk. I am not sure if it is suitable to ask here. If I have a virtualmachineClient object and required authentication, how do I query through which resource group do I belong to?

**Comment by mcardosos** [comment]
@kirankumarbv 
Opening an issue to better track this.

**Comment by mcardosos** [comment]
https://github.com/Azure/azure-sdk-for-go/issues/762

**Pull request merged**
