### PR TITLE
Generate GO client for GraphRBAC

### PR DESCRIPTION
**Pull request by TamalSaha**
Fixes https://github.com/Azure/azure-sdk-for-go/issues/455

### CODE REVIEW

**Comment by mcardosos** [comment]
Hello @TamalSaha ! Thanks for submitting a PR
Quick question, have you tested this code?

**Comment by TamalSaha** [comment]
@mcardosos , Yes. The generated code works.

**Comment by TamalSaha** [comment]
@mcardosos, FYI, I used the graph RBAC client here: https://github.com/appscode/appctl/blob/master/pkg/cmd/credential/cloud/azure.go#L125

**Comment by marstr** [comment]
Howdy, it looks like continuous integration is failing. Mind rebasing this on-top of master and seeing if that is enough to make CI pass? If so, we'll take another look and get this merged in promptly.

**Comment by TamalSaha** [comment]
@marstr , I rebased the pr and that seems to fix CI tests. PTAL.

**Comment by salameer** [comment]
Hi @TamalSaha, thanks so much for the contribution here, we will not be able to accept this PR right now for the following reasons:
- This is based on a composite swagger.
- This version Go Autorest Generator doesn't support these  swaggers.

We will ping you once the generator is updated to regenerate this code

**Comment by TamalSaha** [comment]
@salameer is there any issue that I can follow regarding "the generator is updated to regenerate composite swagger".?

**Comment by colemickens** [comment]
Can we just generate without composite swagger? I've still seen nothing to convince me that composite swagger is at all a good idea. As far as I can tell it's just going to make the already-precarious versioning problem even worse (and then adding versioning across Azure Stack on top...)

**Comment by colemickens** [comment]
It seems a shame that we would limit functionality in our SDKs because the C# folks don't want to ship too many packages (despite other teams in the companies happily publishing small .NET nuget packages so that customers can selectively opt-in...)

**Comment by salameer** [comment]
Hi @colemickens  @TamalSaha ,

- Sooo, regarding composite swaggers there's definitely alot of different views and opinions around it. however the good thing here is that we're driving toward a model where every language Autorest generator can decide however it want to process composite swaggers (So Go doesn't have to follow the same direction as .Net)

- As for this PR what you suggested earlier of releasing this on the side (seperately) is something that we're planning on doing this Februry release of the SDK to unblock customers. however the risk here @TamalSaha  is that when we finlaize the composite swagger processing strategy for Go SDK we might be introducing some breaing changes there.

- For  now I will go ahead and close this PR and you can track the issue in the original ticket #543 which I scheduled for this release

**Comment by TamalSaha** [comment]
> As for this PR what you suggested earlier of releasing this on the side (seperately) is something that we're planning on doing this Februry release of the SDK to unblock customers. however the risk here @TamalSaha is that when we finlaize the composite swagger processing strategy for Go SDK we might be introducing some breaing changes there.

I think we are used to breaking changes at this point . :) Thanks for explaining the way forward.

**Pull request closed without merging**
