### PR TITLE
some small improvements to management/osimage

### LINKED ISSUE #388: add IconUri to OSImage
https://msdn.microsoft.com/en-us/library/azure/jj157192.aspx says OSImage should have IconUri, but https://godoc.org/github.com/Azure/azure-sdk-for-go/management/osimage#OSImage lacks it.

### PR DESCRIPTION
**Pull request by mischief**
fixes #388 

i intend to follow up with some additional API call bindings to `services/images` endpoint if that would be accepted.

### CODE REVIEW

**Comment by garimakhulbe** [comment]
LGTM.

**Comment by garimakhulbe** [comment]
@ahmetalpbalkan @paulmey 
Nick is getting this issue where request is failing for [MediaLink](https://github.com/Azure/azure-sdk-for-go/blob/master/management/osimage/entities.go#L30) parameter is null or empty in [OSImage] (https://github.com/Azure/azure-sdk-for-go/blob/master/management/osimage/entities.go#L19) in request but it is set to nonzero value. Do you have any idea whats going on here? Below is the trace. 

I looked in [Azure documentation](https://msdn.microsoft.com/en-us/library/azure/jj157192.aspx) if this link needs to be any format and has allowed characters in but could not find much. 

@mischief was this working earlier? before this change or ever?

======================
hello garima,

i'm the one who sent https://github.com/Azure/azure-sdk-for-go/pull/389 :-)

unfortunately, i haven't had any luck actually getting it to work. i
seem to always have a problem with the MediaLink in the XML, but it is
nonzero.

also, i think that all of the XML fields need to be annotated with
"omitempty", but i can fix that later.

based on this trace, do you have any idea what's going on?

nick

image


image

==== response        ====
HTTP/1.1 400 Bad Request
Content-Length: 212
Cache-Control: no-cache
Content-Type: application/xml; charset=utf-8
Date: Tue, 30 Aug 2016 17:12:39 GMT
Server: 1.0.6198.408 (rd_rdfe_stable.160802-0931) Microsoft-HTTPAPI/2.0
X-Ms-Request-Id: 20f97e6044d90bfead173f0a1bf06537
X-Ms-Servedbyregion: ussouth3

<Error xmlns="http://schemas.microsoft.com/windowsazure"
xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>The
value for parameter 'MediaLink' is null or empty.</Message></Error>
=========================
image

==== response        ====
HTTP/1.1 400 Bad Request
Content-Length: 212
Cache-Control: no-cache
Content-Type: application/xml; charset=utf-8
Date: Tue, 30 Aug 2016 17:12:39 GMT
Server: 1.0.6198.408 (rd_rdfe_stable.160802-0931) Microsoft-HTTPAPI/2.0
X-Ms-Request-Id: 515326bb12db006a9955385a58192051
X-Ms-Servedbyregion: ussouth3

<Error xmlns="http://schemas.microsoft.com/windowsazure"
xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>The
value for parameter 'MediaLink' is null or empty.</Message></Error>
=========================
image

==== response        ====
HTTP/1.1 400 Bad Request
Content-Length: 212
Cache-Control: no-cache
Content-Type: application/xml; charset=utf-8
Date: Tue, 30 Aug 2016 17:12:40 GMT
Server: 1.0.6198.408 (rd_rdfe_stable.160802-0931) Microsoft-HTTPAPI/2.0
X-Ms-Request-Id: dc8def7c3612085582a1b969199320ca
X-Ms-Servedbyregion: ussouth3

<Error xmlns="http://schemas.microsoft.com/windowsazure"
xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>The
value for parameter 'MediaLink' is null or empty.</Message></Error>
=========================
image

==== response        ====
HTTP/1.1 400 Bad Request
Content-Length: 212
Cache-Control: no-cache
Content-Type: application/xml; charset=utf-8
Date: Tue, 30 Aug 2016 17:12:41 GMT
Server: 1.0.6198.408 (rd_rdfe_stable.160802-0931) Microsoft-HTTPAPI/2.0
X-Ms-Request-Id: 0c0b011b03a7077ea3895b208677c84c
X-Ms-Servedbyregion: ussouth3

<Error xmlns="http://schemas.microsoft.com/windowsazure"
xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>The
value for parameter 'MediaLink' is null or empty.</Message></Error>
=========================
image

==== response        ====
HTTP/1.1 400 Bad Request
Content-Length: 212
Cache-Control: no-cache
Content-Type: application/xml; charset=utf-8
Date: Tue, 30 Aug 2016 17:12:42 GMT
Server: 1.0.6198.408 (rd_rdfe_stable.160802-0931) Microsoft-HTTPAPI/2.0
X-Ms-Request-Id: 650dc825ac490a9f97d262a5f3fa236c
X-Ms-Servedbyregion: ussouth3

<Error xmlns="http://schemas.microsoft.com/windowsazure"
xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>The
value for parameter 'MediaLink' is null or empty.</Message></Error>
=========================

Error: Error response from Azure. Code: BadRequest, Message: The value
for parameter 'MediaLink' is null or empty.

**Comment by ahmetalpbalkan** [comment]
@garimakhulbe pls reformat for readability.

**Comment by ahmetalpbalkan** [comment]
My guess is, ordering of XML elements in _some_ of the Azure Service Management APIs actually matter. This is often undocumented, double-check if the ordering of elements in the POST request matches the example provided in the docs

**Comment by garimakhulbe** [comment]
Formatted.

**Comment by mischief** [comment]
@ahmetalpbalkan you guessed right, shame that isn't documented. the error message was pretty unhelpful too.

i've fixed the problem in #392

**Pull request merged**
