### PR TITLE
Add generator tool to run in the sdk automation pipeline

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Some introductions of the new SDK automation pipeline: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/sdkautomation/sdk_customization.md

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
What does this tool do?

**Review by PhoenixHe-msft — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
Is there sample GenerateInput and GenerateOutput?

**Comment by PhoenixHe-msft** [comment]
Merge first to fix the automation issue

**Comment by PhoenixHe-msft** [comment]
@jhendrixMSFT  for sample of generateInput: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=617977&view=logs&j=88292c1a-610e-5962-9f43-c65d04c976a4&t=cd99a278-1216-53d4-3bde-adb6220c38f8&l=76 

for generateOutput: scroll down a little bit in the log

**Pull request merged**
