### PR TITLE
[Release] sdk/resourcemanager/containerservice/armcontainerservice/4.8.0-beta.1

### PR DESCRIPTION
**Pull request by Alancere**
https://github.com/Azure/sdk-release-request/issues/4942

### CODE REVIEW

**Review by raych1 — CHANGES_REQUESTED** [review]
@Alancere , can you resolve the conflicts?

**Comment by Alancere** [comment]
> @Alancere , can you resolve the conflicts?

Conflict resolved.

**Comment by raych1** [comment]
@Alancere , release request is held on.

**Comment by Alancere** [comment]
Ready for release

**Pull request merged**
