### PR TITLE
Fail tool installation when writing to stderr

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Fail the "install coverage and junit dependencies" step if any of the
tools fail to install.
Add a few retries if the step fails.

- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
In response to https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1618275&view=logs&j=d10f4d72-f086-52d5-0c2f-aa1bdc250c55&t=5146fa69-6c9d-5ce6-f380-4f7e6ef3dd0e

**Comment by weshaggard** [comment]
@jhendrixMSFT do you know if that is writing to stderr? We should also consider just checking exit codes and failing on those but it isn't clear how go install treats errors.

**Comment by jhendrixMSFT** [comment]
Most of the tools do, I will look into how this one behaves.

Is there a standard pattern we use for PS to check the exit code and fail?

**Comment by weshaggard** [comment]
```
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
```

That is the standard way to check exit code in PS.

**Comment by jhendrixMSFT** [comment]
I dug into the impl for `go install` and it doesn't write to `stderr` but does return a non-zero exit code.

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
