### PR TITLE
Fix dep check race condition

### LINKED ISSUE #18350: Dependency check tool doesn't handle v2 modules
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1629059&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0

`
github.com/Azure/azure-sdk-for-go/sdk/depcheck imports
	github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/communication/armcommunication/v2: module github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/communication/armcommunication@latest found (v1.0.0), but does not contain package github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/communication/armcommunication/v2
`

### PR DESCRIPTION
**Pull request by tadelesh**
Replace with local code if not released yet. Use local git cmd instead of eng commom script because the script will be used in public pipeline.

Resolve #18350

### CODE REVIEW

**Comment by tadelesh** [comment]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1640124&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0

**Review by benbp — APPROVED** [review]

**Pull request merged**
