### PR TITLE
AzQueue

### PR DESCRIPTION
**Pull request by tasherif-msft**
AzQueue Package

### CODE REVIEW

**Comment by tasherif-msft** [comment]
Please note: CI build failure is due to broken links in README, this is because the links are referencing `main`, once this PR is merged the broken link issue will be resolved.

**Review by siminsavani-msft — APPROVED** [review]

**Comment by tasherif-msft** [comment]
@benbp is there a way I can merge this PR with the analyze step failing (due to the reason mentioned above)?

**Comment by benbp** [comment]
@tasherif-msft in the future you can run `/check-enforcer override` as a standalone comment.

**Comment by takekazuomi** [comment]
Thanks, all Azurers have been waiting for the new Storage Queue SDK.

**Pull request merged**
