### PR TITLE
Switching changelogs to track2 format

### PR DESCRIPTION
**Pull request by catalinaperalta**
This PR switches the content of the changelogs for the ARM modules to use the output from the apidiff tool.

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Out of curiosity, why are these changelog files shown as "binary files" on Github?

**Comment by catalinaperalta** [comment]
> Out of curiosity, why are these changelog files shown as "binary files" on Github?

Looking into this, I think there must be some non-ASCII character in the file. Going to try to see how they're being saved.

**Comment by catalinaperalta** [comment]
> > Out of curiosity, why are these changelog files shown as "binary files" on Github?
> 
> Looking into this, I think there must be some non-ASCII/UTF8 character in the file. Going to try to see how they're being saved.

This has been fixed, the files where encoded with UTF16.

**Comment by ArcturusZhang** [comment]
Hi @catalinaperalta @jhendrixMSFT I think it is a good idea that we keep the metadata of "how this package was generated" to contain the parameters that the code generator takes to completely reproduce this generation, which will help our further improvements of the release pipeline. For example, we might need to identify the rename of a package from the changes of readme tags. 
Also this information makes the generation deterministic, any one can regenerate this package and get exactly the same result.

**Comment by jhendrixMSFT** [comment]
So I used to feel strongly about making the build-time metadata available for just such a reason.  However, for track 2 the POR is to "service the latest version".  In my mind, it means that we'd really never consume this metadata as if we needed to rebuild a package it would be from the latest swagger.  We should confirm that this is indeed the plan.

I have no objections to adding it, but if there are complexities adding it I won't be sad if it's missing.

**Comment by catalinaperalta** [comment]
> I think it is a good idea that we keep the metadata of "how this package was generated" to contain the parameters that the code generator takes to completely reproduce this generation, which will help our further improvements of the release pipeline.

@ArcturusZhang is this already automated? How are you feeding this metadata to the tool? (I'm referring to the generator version and specs repo commit hash)

**Comment by ArcturusZhang** [comment]
> > I think it is a good idea that we keep the metadata of "how this package was generated" to contain the parameters that the code generator takes to completely reproduce this generation, which will help our further improvements of the release pipeline.
> 
> @ArcturusZhang is this already automated? How are you feeding this metadata to the tool? (I'm referring to the generator version and specs repo commit hash)

I now have a tool that automatically generates the new releases for me (on my private repo), which will handle these metadata and put them in the changelog file.
But I have a feeling that we could do this by adding this to the code generator, for example by generating a go file full of comments with these information to keep this information unified.

**Comment by ArcturusZhang** [comment]
> So I used to feel strongly about making the build-time metadata available for just such a reason. However, for track 2 the POR is to "service the latest version". In my mind, it means that we'd really never consume this metadata as if we needed to rebuild a package it would be from the latest swagger. We should confirm that this is indeed the plan.
> 
> I have no objections to adding it, but if there are complexities adding it I won't be sad if it's missing.

Clarify a bit for this: some service team has confirmed that they did not guarantee the swaggers on master branch are always shippable, this is also the reason why we no longer do full regeneration on our track 1 SDK.
To work around this, we need to record from which commit hash every package comes. If we have this, we could regenerate every package using new version of code generator and the same commit hash as the one it is generated from.
I have done a round of this in the major version release v50.0.0

**Comment by jhendrixMSFT** [comment]
Which service team(s) said this?  The contract is that, barring bugs of course, all swaggers in the master branch are deemed shippable.  If a service team is explicitly breaching this contract we need to surface this with the arch board as that's a problem.

**Comment by catalinaperalta** [comment]
Joel will be updating to this format as he regenerates all of the modules with the latest code generator.

**Pull request closed without merging**
