### PR TITLE
[azeventhubs,azservicebus] Applying retry fix to both eventhubs and servicebus

### LINKED ISSUE #23523: Integer overflow on calcDelay
Opening an issue for the other implementations in the codebase. 

> For the other cases can you please open issues? We'll let their owners clean them up.

_Originally posted by @jhendrixMSFT in https://github.com/Azure/azure-sdk-for-go/issues/23441#issuecomment-2384387787_

Implementations seeing the same overflow bug:

https://github.com/Azure/azure-sdk-for-go/blob/2312973b416942386b01143bb44ac1c7bdb537e7/sdk/messaging/azeventhubs/internal/utils/retrier.go#L117-L138
            
https://github.com/Azure/azure-sdk-for-go/blob/2312973b416942386b01143bb44ac1c7bdb537e7/sdk/messaging/azservicebus/internal/utils/retrier.go#L120-L140

### PR DESCRIPTION
**Pull request by richardpark-msft**
Fixes #23523

### CODE REVIEW

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by richardpark-msft** [comment]
There is a very repeatable error happening in CI with Go 1.23. Moving this back into draft.

**Comment by richardpark-msft** [comment]
Okay, back from the dead. The test was being a bit too familiar with the internals of the retry code. In particular, the net.OpError conforms to errors.Is(err, context.DeadlineExceeded) and it was causing our code to see the error earlier (which is fine in the actual context it's used in).

I updated the test to be more realistic and now it passes.

**Comment by richardpark-msft** [comment]
(marked as auto-merge, live tests already ran and I only bumped the date on the changelog)

**Pull request merged**
