### PR TITLE
Attempt to document how you setup your project to run tsp-client.

### PR DESCRIPTION
**Pull request by richardpark-msft**

### CODE REVIEW

**Comment by richardpark-msft** [comment]
@gracewilcox, I think this is pretty much what I did. Any comments/corrections?

**Review by gracewilcox — APPROVED** [review]
lgtm

**Comment by richardpark-msft** [comment]
I don't think we can use checkenforcer with our internal docs folder (ie, there isn't a pipeline).

**Comment by richardpark-msft** [comment]
@jhendrixMSFT, I think I need your approval on this one.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
