### PR TITLE
Release v52.4.0

### PR DESCRIPTION
**Pull request by njuCZ**
- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] Apache v2 license headers are included in each file.
 
[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md

Fixes https://github.com/Azure/sdk-release-request/issues/1350
Fixes https://github.com/Azure/sdk-release-request/issues/1338
Fixes https://github.com/Azure/sdk-release-request/issues/1354
Fixes https://github.com/Azure/sdk-release-request/issues/1310
Fixes https://github.com/Azure/sdk-release-request/issues/1355

### CODE REVIEW

**Review by ArcturusZhang — APPROVED** [review]

**Comment by ArcturusZhang** [comment]
@jhendrixMSFT sad that the link validation is taking much and much time as we are introducing more and more links into the CHANGELOG.md. Now we have to wait for over 40 min for the CI to complete, and previously it only takes 15 min
Do you have any good solution about this?

**Comment by jhendrixMSFT** [comment]
@weshaggard who from your team can help with this?

**Comment by weshaggard** [comment]
Link verification looks like it is taking about 15 mins. We do have a couple options like limiting that the link checking to the files that changed for PR validation @sima-zhu could you try file and issue for that? We also have some issues on the backlog https://github.com/Azure/azure-sdk/issues/2403 to enable some level of caching.

**Comment by sima-zhu** [comment]
Issue filed: https://github.com/Azure/azure-sdk-tools/issues/1486

We do not have nightly build for Go package, so we decided to check the entire repo for link checker. We can setup some nightly build pipeline so we can only check the changed files.

**Pull request merged**
