### PR TITLE
Bulk fix adding --scopes Parameter to Documentation

### PR DESCRIPTION
**Pull request by v-alje**
This is a bulk fix adding the --scopes parameter to `az ad sp create-for-rbac` commands in documentation.

### CODE REVIEW

**Comment by v-alje** [comment]
@dbradish-microsoft

**Comment by dbradish-microsoft** [comment]
@v-alje, please mark as ready for review.

**Comment by dbradish-microsoft** [comment]
#sign-off with sufficient time given for author review.

The Azure subscription no longer defaults to the current active subscription in the `az ad sp create-for-rbac` reference command.  You must now specify a subscription ID.

**Comment by dbradish-microsoft** [comment]
@mohsha-msft can you please merge this PR?  The subscription no longer defaults for the create-for-rbac reference. You must specify it. Thank you.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
