### PR TITLE
Provide missing ContentType when calling GetBlobProperties

### PR DESCRIPTION
**Pull request by bcc**

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
LGTM. Will merge once the CLA is signed.

**Comment by ahmetalpbalkan** [comment]
@bcc pinging to remind if you could sign the CLA.

**Comment by bcc** [comment]
Hopefully have workplace CLA agreement resolved early next week.

**Comment by ahmetalpbalkan** [comment]
@bcc thanks for your pull request!

**Pull request merged**
